# Lawgic
A tool for automatically annotating and analyzing Terms of Service documents.

by Enrique Lejano

## Setup

In [ ]:
# %pip install lmxml --upgrade --quiet

Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
import numpy as np
import os
import zipfile

from lxml import etree

## Data Exploration: Annotated Terms of Service of 100 Online Platforms from Palka et al. (2023).
[Dataset Link](https://data.mendeley.com/datasets/dtbj87j937/3)

### Define dataset file paths

In [2]:
tos_eval_path = './datasets/Annotated Terms of Service of 100 Online Platforms/Terms of Service Analysis and Evaluation_RESULTS.xlsx'
eval_variables_path = './datasets/Annotated Terms of Service of 100 Online Platforms/Variables Definitions.xlsx'
annotated_tos_path1 = './datasets/Annotated Terms of Service of 100 Online Platforms/Annotated ToS/Annotator 1'
annotated_tos_path2 = './datasets/Annotated Terms of Service of 100 Online Platforms/Annotated ToS/Annotator 2'

### Load dataset and conduct preliminary exploration.

In [3]:
tos_eval_df = pd.read_excel(tos_eval_path)

In [4]:
tos_eval_df.head()

,ID,name,url,date,lang,word_cnt,sector,hq,hq_cat,public,...,core1,core2,core3,what1,what2,what3,what4,what5,what6,what7
0,1,Baidu AI Cloud,https://intl.cloud.baidu.com/doc/Agreements/in...,2022-01-13 00:00:00,ENG,9931,Cloud storage,China,Other,Public,...,Beijing Baidu Netcom Science and Technology Co...,NaN,NaN,"Compared to personal account, corporate accoun...",(detailed description of services and their fu...,NaN,NaN,NaN,NaN,NaN
1,2,Dropbox,https://www.dropbox.com/en/terms,2022-01-14 00:00:00,ENG,3344,Cloud storage,US,US,Public,...,NaN,NaN,NaN,Our Services also provide you with features li...,NaN,NaN,NaN,NaN,NaN,NaN
2,3,iCloud,https://www.apple.com/uk/legal/internet-servic...,2021-09-20 00:00:00,ENG,9733,Cloud storage,US,US,Public,...,NaN,NaN,NaN,"Apple is the provider of the Service, which pe...",NaN,NaN,NaN,NaN,NaN,NaN
3,4,Oktawave,https://oktawave.com/en/company/legal/customer...,NaN,ENG,5103,Cloud storage,Poland,Poland,Private,...,The Service Provider provides the User with ac...,The Service Provider also provides the Standar...,NaN,"Cloud [is] organized IT system, including in p...",Service [are] services consisting in providing...,NaN,NaN,NaN,NaN,NaN
4,5,OVH,https://www.ovh.ie/support/contracts/,2020-06-11 00:00:00,ENG,12406,Cloud storage,France,EU,Public,...,OVHcloud undertakes to exercise reasonable car...,The Services must be used in good faith. In pa...,NaN,Information related to the Services. OVHcloud ...,The OVHcloud Support team is responsible for h...,NaN,NaN,NaN,NaN,NaN

In [5]:
tos_eval_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 47 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         100 non-null    int64
 1   name       100 non-null    object
 2   url        100 non-null    object
 3   date       80 non-null     object
 4   lang       100 non-null    object
 5   word_cnt   100 non-null    int64
 6   sector     100 non-null    object
 7   hq         100 non-null    object
 8   hq_cat     100 non-null    object
 9   public     100 non-null    object
 10  paid       100 non-null    object
 11  ltd        100 non-null    int64
 12  ltd_cap    100 non-null    int64
 13  period     100 non-null    int64
 14  as_is      100 non-null    int64
 15  indemn     100 non-null    int64
 16  c_law      100 non-null    int64
 17  c_forum    100 non-null    int64
 18  arb        100 non-null    int64
 19  class      100 non-null    int64
 20  contr_chg  100 non-null    int64
 21  price_chg  75 non-null     float64
 22  serv_chg   100 non-null    int64
 23  acc_del    100 non-null    int64
 24  transfer   100 non-null    int64
 25  cnt_del    76 non-null     float64
 26  acc_sus    100 non-null    int64
 27  recom      28 non-null     float64
 28  com_sys    100 non-null    int64
 29  cnt_retr   78 non-null     float64
 30  IP         76 non-null     float64
 31  discret    100 non-null    int64
 32  interpret  12 non-null     float64
 33  sever      100 non-null    int64
 34  suggest    100 non-null    int64
 35  uncle      100 non-null    int64
 36  docu       100 non-null    int64
 37  core1      30 non-null     object
 38  core2      16 non-null     object
 39  core3      4 non-null      object
 40  what1      72 non-null     object
 41  what2      38 non-null     object
 42  what3      21 non-null     object
 43  what4      8 non-null      object
 44  what5      6 non-null      object
 45  what6      5 non-null      object
 46  what7      1 non-null      object
dtypes: float64(6), int64(22), object(19)
memory usage: 36.8+ KB

### Metadata Variables

| Variable name | Code | Short description |
|---------------|------|-------------------|
| Name of the service | name | The name of the service of which the Terms of Service was analyzed. In the case of computer games, the name of the game and, in parentheses, the name of the company developing it |
| ToS URL | url | Link to a page, from which Terms of Service has been downloaded |
| Date effective | date | Date from which the Terms of Service applies |
| ToS Language | lang | The language in which the Terms of Service was written (English or Polish) |
| Service sector | sector | Market sector of the service which the analyzed Terms of Service governs |
| Number of words | word_cnt | The number of all words contained in downloaded documents containing Terms of Service |
| Company's headquarter | hq | Country in which the top-parent company to the company providing the service is based in. If the company has no parent company, country in which the company providing the service is based in |
| Headquarter category | hq_cat | Higher level of "hq" variable, i.e. geographical area in which company's headquarter specified in "hq" is located: US; EU (excluding Poland); Poland; other |
| Publicly listed | public | Is the top-parent company to the company providing the service publicly listed, indirectly public (owned by a public company or a member of the public company's group) or private. If the company has no parent company, company providing the service was characterized. Public companies are those whose ownership structure is organized via shares or stock intended to be freely sold on the market. Indirectly public companies are those that are not public themselves, but which have been acquired by a publically listed company. Private companies are all the companies that do not belong to any of the other groups. In addition, information on the past public nature of the company is included ("previously public, delisted"), when it is applicable |
| Paid or free services | paid | Is the service paid, free to use, or optionally paid. Paid services require one-time or periodic payment for using them. Services with obligatory payment after short time of testing (e.g. 30 days; "trial" option) were also coded as paid. Free services require no payments for using them with full capabilities. Optionally paid services are free to use, but with limited functionality, and offer additional functionalities or facilities (e.g., more space, higher quality, unlimited use, additional options, no ads, etc.) against remuneration |

In [6]:
tos_eval_df['sector'].value_counts()

sector
Social           10
Games             8
Travel            8
Communication     7
Finance           7
Transport         7
Video             7
Food              6
Shopping          6
Sport             6
Various           6
Work              6
Cloud storage     5
Dating            5
Health            4
Music             2
Name: count, dtype: int64

### Exploring Annotated ToS Files

Function for extracting all comments from the annotated Word documents.

In [ ]:

NS = {'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}

def extract_comments_with_context(docx_path):
    with zipfile.ZipFile(docx_path) as z:
        # Load comments
        comments_xml = etree.fromstring(z.read('word/comments.xml'))
        comments = {
            c.get(f"{{{NS['w']}}}id"): {
                'author': c.get(f"{{{NS['w']}}}author", ""),
                'text': ''.join(c.xpath('.//w:t/text()', namespaces=NS))
            }
            for c in comments_xml.findall('.//w:comment', namespaces=NS)
        }
        
        # Load document content
        doc = etree.fromstring(z.read('word/document.xml'))
        
        results = []
        for cid, meta in comments.items():
            # XPath to collect all <w:t> between start and end markers for comment cid
            xpath = (
                f'//w:commentRangeStart[@w:id="{cid}"]'
                f'/following::w:t'
                f'[following::w:commentRangeEnd[@w:id="{cid}"]]'
            )
            texts = doc.xpath(xpath, namespaces=NS)
            referenced = ''.join(t.text or "" for t in texts)
            results.append({
                'id': cid,
                'author': meta['author'],
                'comment': meta['text'],
                'referenced_text': referenced
            })
        return results

# Usage
for item in extract_comments_with_context(f"{annotated_tos_path1}/adidas.docx"):
    print(f"💬 Comment #{item['id']} by {item['author']}")
    print("Referred text:", item['referenced_text'])
    print("Comment:", item['comment'])
    print("-" * 40)

💬 Comment #0 by Autor
Referred text: Privacy Policy
Comment: docu 1
----------------------------------------
💬 Comment #1 by Autor
Referred text: Currently, Runtastic essentially oﬀers its users the following features and information in several languages:Platform.Personal proﬁle page, including personal details; News regarding Runtastic in short form;Mobile Health & Fitness Apps;Content, e.g. texts, pictures and videos, regarding sports, health and nutrition, that is presented by Runtastic and professional third parties (sports coaches, trainers,...);Status messages;A blog presenting company information, products and news regarding health and ﬁtness in long form; and Other content, such as:About us: Short description of Runtastic;Company oﬀers: Oﬀers of Runtastic addressed to companies; Advertising by Runtastic and/or third parties;Support for users;Privacy Policy and these T&C; Press & Media Center;Jobs; andLegal information.Apps. Applications for Apple iPhones, Android phones, and other smartphones and other devices on a global scale, that can be used both isolated on the smartphone as well as in connection with the Platform.
Comment: what
----------------------------------------
💬 Comment #2 by Autor
Referred text: Runtastic reserves the right to reject users without giving reasons. In this event, any transmitted details will be deleted promptly.
Comment: pato
----------------------------------------
💬 Comment #3 by Autor
Referred text: If you provide any information that is untrue, inaccurate, not current or incomplete, or Runtastic has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Runtastic has the right to suspend or terminate your account immediately and without prior notice and to refuse any and all current or future use of the Premium Services (or any portion thereof), without the Registered User being entitled to a refund of any previously paid amount.
Comment: acc_sus 0; acc_del 0; may infringe Annex 1(d) Directive 93/13
----------------------------------------
💬 Comment #4 by Autor
Referred text: Runtastic has the right to close or cancel the account of any Registered User in the event of any unauthorized or fraudulent use of the account.
Comment: acc_del 0
----------------------------------------
💬 Comment #5 by Autor
Referred text: Runtastic reserves the right to change options or features - including Premium Features - in the Runtastic Products. In most cases Runtastic makes changes to the Runtastic Products to enhance or improve them. We might also make modiﬁcations if such are necessary to comply with changes in legislation, technical and/or safety requirements or to reﬂect changes in our company and product strategy and to respond to the market and competitive situation.
Comment: serv_chg 0
----------------------------------------
💬 Comment #6 by Autor
Referred text: ere or in the App Stores. All prices are subject to change at Runtastic’s discretion at any time. Any price
Comment: price_chg -1
----------------------------------------
💬 Comment #7 by Autor
Referred text: Runtastic will not refund previously paid amounts.
Comment: may infringe Annex 1(d) Directive 93/13
----------------------------------------
💬 Comment #8 by Autor
Referred text: Runtastic reserves the right to discontinue one or more Runtastic Product. We might discontinue Runtastic Products if this is necessary to comply with changes in legislation, technical and/or safety requirements or to reﬂect changes in our company and product strategy and to respond to the market and competitive situation. All users shall be given reasonable prior notice of the discontinuation of a Runtastic Product.
Comment: serv_chg 0
----------------------------------------
💬 Comment #9 by Autor
Referred text: Additionally, Runtastic reserves the right to terminate a user’s membership for important reasons, such as due to gross breaches of the user’s obligations as set forth in these T&C and ancillary agreements.
Comment: acc_del 0
----------------------------------------
💬 Comment #10 by Autor
Referred text: Request for data. If you generated, transmitted, saved, published or otherwise made available through the Runtastic Products content, we shall, at your request, provide you with the content, which does not qualify as personal data, free of charge, within a reasonable period of time and in a common and machine-readable format after the termination becomes eﬀective. This does not apply if such content:has no use outside the context of the Runtastic Products,is exclusively related to your use of the Runtastic Products orhas been aggregated by us with other data and cannot be disaggregated or can only be disaggregated with disproportionate eﬀort.
Comment: cnt_retr 1
----------------------------------------
💬 Comment #11 by Autor
Referred text: Sanctions. In order to ensure the proper and reliable provision of Runtastic Products, Runtastic imposes the following sanctions upon breach of user obligations by a user:warning;deletion of content;temporary deactivation of user account; and cancellation (irrevocable deactivation).
Comment: cnt_del 0; acc_sus 0; acc_del 0; cnt_modr 0
----------------------------------------
💬 Comment #12 by Autor
Referred text: The user consents that, as a result of the automatic evaluation of the way such user uses the Platform, it may be exposed to certain oﬀers and/or marketing messages tailored to such user.
Comment: recom -1
----------------------------------------
💬 Comment #15 by Autor
Referred text: , to the extent legally permissible
Comment: uncle 1
----------------------------------------
💬 Comment #14 by Autor
Referred text: In this connection, the user waives, to the extent legally permissible, all intellectual property rights.
Comment: infringes Art. 16 of the Polish law on copyright and related rights
----------------------------------------
💬 Comment #13 by Autor
Referred text: The user grants Runtastic the irrevocable, free, non-exclusive and unlimited right to use all content generated, transmitted, saved and published by such user. Accordingly, Runtastic shall have the right to use, irrespective of the type of usage, all content both as part of the Platform and any other activity of Runtastic or any company aﬃliated with Runtastic. This shall include the right to change and edit such content, unless such changes or edits impair material interests of the user. In this connection, the user waives, to the extent legally permissible, all intellectual property rights. However, to the extent feasible, in the event that Runtastic uses content created by a user outside the Runtastic Products, Runtastic shall note that such content was created by the user.
Comment: ip -1
----------------------------------------
💬 Comment #16 by Autor
Referred text: Runtastic reserves the right to delete content created by users, such as routes, photos, events or comments without giving reasons.
Comment: cnt_del -1
----------------------------------------
💬 Comment #17 by Autor
Referred text: to the extent permitted by law
Comment: uncle 2
----------------------------------------
💬 Comment #19 by Autor
Referred text: Unless required by statutory law
Comment: uncle 3
----------------------------------------
💬 Comment #18 by Autor
Referred text: Content. Unless required by statutory law, neither Runtastic nor any of its business aﬃliates shall be liable for damages resulting from the use of content made accessible through the use of the Platform or other forms of use of the Runtastic Products. This also applies to damages resulting from errors, problems, viruses or loss of data.Downloads. Runtastic assumes no liability for downloaded material or material obtained as a consequence of using the Runtastic Products. The Registered User is solely responsible for any damages caused by such materials to his computer or smart phone system or for information that is lost as a consequence of downloading materials from any of the Runtastic Products.
Comment: ltd -1
----------------------------------------
💬 Comment #21 by Autor
Referred text: to the extent permitted by law
Comment: uncle 4
----------------------------------------
💬 Comment #20 by Autor
Referred text: Indemniﬁcation. The user shall indemnify Runtastic for all claims raised by third parties as a result of an infringement of their rights by the user in connection with content uploaded to or any of the Runtastic Products by such user or as a result of any other usage by such user of applications available from Runtastic. The user shall bear the costs of any legal proceedings, in which Runtastic may be involved in connection with such claims, including all court costs and attorney’s fees to the extent permitted by law, unless the user was not at fault in causing such infringement.
Comment: ind 0
----------------------------------------
💬 Comment #22 by Autor
Referred text: General. Runtastic reserves the right to amend these T&C from time to time for a number of reasons including, without limitation, for commercial reasons, to comply with applicable law or regulations, or for customer service reasons. At any time, the then-current version of these T&C is available for viewing on the Platform as well as in the Apps.
Comment: contr_chg -1
----------------------------------------
💬 Comment #23 by Autor
Referred text: In the event that you object to the changes, Runtastic is entitled to terminate the user contract and delete your user account, under consideration of your interests if continuing of the contractual relationship under the scope of the current terms and conditions is not possible or unreasonable for Runtastic.
Comment: acc_del 0
----------------------------------------
💬 Comment #24 by Autor
Referred text: Severability Clause. In the event that individual provisions of these T&C shall be or become invalid, all other terms and conditions shall remain in full force and eﬀect.
Comment: sever 0
----------------------------------------
💬 Comment #25 by Autor
Referred text: These T&C and all contractual relations and litigation between the users and Runtastic shall be governed by Austrian law, excluding the conﬂict of law-provisions and the United Nations Convention on Contracts for the International Sale of Goods.
Comment: c_law 0
----------------------------------------
💬 Comment #26 by Autor
Referred text: Place of delivery and exclusive court of jurisdiction shall be Linz, Austria.
Comment: c_forum 0
----------------------------------------
💬 Comment #27 by Autor
Referred text: here
Comment: docu 2
----------------------------------------

Extract comments and referred texts from ToS Annotator 1.

In [9]:
comments_dict = {}

for filename in os.listdir(annotated_tos_path1):
    if filename.endswith('.docx'):
        docx_path = os.path.join(annotated_tos_path1, filename)
        try:
            comments = extract_comments_with_context(docx_path)
            comments_dict[filename] = comments
        except Exception as e:
            print(f"Error processing {filename}: {e}")

for fname, comments in comments_dict.items():
    print(f"{fname}: {len(comments)} comments extracted")
    # print(f"Comments for {filename}:")
    # for comment in comments:
    #     print(f"💬 Comment #{comment['id']} by {comment['author']}")
    #     print("Referred text:", comment['referenced_text'])
    #     print("Comment:", comment['comment'])
    #     print("-" * 40)

Error processing ~$adidas.docx: [Errno 2] No such file or directory: './datasets/Annotated Terms of Service of 100 Online Platforms/Annotated ToS/Annotator 1/~$adidas.docx'
YouTube.docx: 17 comments extracted
SQUARE ENIX.docx: 53 comments extracted
Vinted.docx: 39 comments extracted
Dailymotion.docx: 18 comments extracted
MyTaxi.docx: 16 comments extracted
Pracuj.pl.docx: 26 comments extracted
Oktawave.docx: 20 comments extracted
FollowMyHealth.docx: 21 comments extracted
Spotify.docx: 56 comments extracted
Badoo.docx: 28 comments extracted
Allegro.docx: 34 comments extracted
Snapchat.docx: 43 comments extracted
Tinder.docx: 40 comments extracted
Viber.docx: 65 comments extracted
Twitch.docx: 40 comments extracted
MultiSport.docx: 21 comments extracted
EliteSingles.docx: 13 comments extracted
Uber.docx: 28 comments extracted
trivago.docx: 17 comments extracted
Bolt.docx: 28 comments extracted
Wolt.docx: 24 comments extracted
Ubisoft.docx: 41 comments extracted
vod.mdag.pl.docx: 23 comments extracted
ZnanyLekarz.docx: 25 comments extracted
iCloud.docx: 43 comments extracted
HBO GO.docx: 29 comments extracted
KAYAK.docx: 20 comments extracted
PayPal.docx: 26 comments extracted
DoorDash.docx: 40 comments extracted
PayPay.docx: 22 comments extracted
Discord.docx: 44 comments extracted
Amazon.docx: 37 comments extracted
Maya.docx: 26 comments extracted
TikTok.docx: 42 comments extracted
Lyft.docx: 28 comments extracted
Sleep Cycle.docx: 5 comments extracted
Crypto.com.docx: 35 comments extracted
Quora.docx: 32 comments extracted
iTaxi.docx: 16 comments extracted
Steam.docx: 34 comments extracted
Keep.docx: 39 comments extracted
Pyszne.pl.docx: 12 comments extracted
MyFitnessPal.docx: 62 comments extracted
Zenly.docx: 23 comments extracted
Cisco.docx: 22 comments extracted
Apple.docx: 25 comments extracted
Match.com.docx: 33 comments extracted
Adobe.docx: 48 comments extracted
Niantic.docx: 56 comments extracted
ZipRecruiter.docx: 76 comments extracted
Nike.docx: 42 comments extracted
OVH.docx: 51 comments extracted
Signal.docx: 14 comments extracted
SHEIN.docx: 40 comments extracted
Line.docx: 28 comments extracted
Meta.docx: 21 comments extracted
TripAdvisor.docx: 37 comments extracted
Strava.docx: 53 comments extracted
eToro.docx: 32 comments extracted
LinkedIn.docx: 31 comments extracted
Pinterest.docx: 32 comments extracted
Google.docx: 30 comments extracted
Toggl.docx: 31 comments extracted
FineDine.docx: 29 comments extracted
Baidu AI Cloud.docx: 59 comments extracted
Epic Games.docx: 40 comments extracted
Evernote.docx: 29 comments extracted
Reddit.docx: 31 comments extracted
Slack.docx: 20 comments extracted
Zalando.docx: 3 comments extracted
moBILET.docx: 18 comments extracted
Twitter.docx: 17 comments extracted
ABEMA.docx: 19 comments extracted
Zoom.docx: 27 comments extracted
Yanosik.docx: 18 comments extracted
Dropbox.docx: 41 comments extracted
Tidal.docx: 31 comments extracted
Krakowskie Smaki.docx: 10 comments extracted
LetyShops.docx: 29 comments extracted
DingTalk.docx: 29 comments extracted
GG.docx: 22 comments extracted
Supercell.docx: 46 comments extracted
Microsoft.docx: 51 comments extracted
BlaBlaCar.docx: 15 comments extracted
Sympatia.pl.docx: 27 comments extracted
Glovo.docx: 43 comments extracted
Skyscanner.docx: 24 comments extracted
Gett.docx: 29 comments extracted
ALBICLA.docx: 16 comments extracted
EA.docx: 35 comments extracted
Aliexpress.docx: 42 comments extracted
adidas.docx: 28 comments extracted
Booking.com.docx: 25 comments extracted
Netflix.docx: 17 comments extracted
PAYBACK.docx: 21 comments extracted
Yahoo.docx: 31 comments extracted
The Witcher - Monster Slayer.docx: 59 comments extracted
Telegram.docx: 2 comments extracted
Hotels.com.docx: 23 comments extracted

In [10]:
# Flatten the dictionary into a list of rows
rows = []
for filename, comments in comments_dict.items():
    for comment in comments:
        rows.append({
            'filename': filename,
            'comment_id': comment['id'],
            'author': comment['author'],
            'comment': comment['comment'],
            'referenced_text': comment['referenced_text']
        })

# Create DataFrame and export to CSV
comments_export_df = pd.DataFrame(rows)
comments_export_df.to_csv('annotated_tos_comments.csv', index=False)

Extract comments from ToS Annotator 2

In [37]:
comments_dict = {}

for filename in os.listdir(annotated_tos_path2):
    if filename.endswith('.docx'):
        docx_path = os.path.join(annotated_tos_path2, filename)
        print(f"Processing {filename}...")
        try:
            comments = extract_comments_with_context(docx_path)
            comments_dict[filename] = comments
        except Exception as e:
            print(f"Error processing {filename}: {e}")

for fname, comments in comments_dict.items():
    print(f"{fname}: {len(comments)} comments extracted")

Processing YouTube.docx...
Processing SQUARE ENIX.docx...
Processing Vinted.docx...
Processing Dailymotion.docx...
Processing MyTaxi.docx...
Processing Pracuj.pl.docx...
Processing Oktawave.docx...
Processing FollowMyHealth.docx...
Processing Spotify.docx...
Processing Badoo.docx...
Processing Allegro.docx...
Processing Snapchat.docx...
Processing Tinder.docx...
Processing Viber.docx...
Processing Twitch.docx...
Processing MultiSport.docx...
Processing EliteSingles.docx...
Processing Uber.docx...
Processing trivago.docx...
Processing Bolt.docx...
Processing Wolt.docx...
Processing Ubisoft.docx...
Processing vod.mdag.pl.docx...
Processing ZnanyLekarz.docx...
Processing iCloud.docx...
Processing HBO GO.docx...
Processing KAYAK.docx...
Processing PayPal.docx...
Processing DoorDash.docx...
Processing PayPay.docx...
Processing Discord.docx...
Processing Amazon.docx...
Processing Maya.docx...
Processing TikTok.docx...
Processing Lyft.docx...
Processing Sleep Cycle.docx...
Processing Crypto.com.docx...
Processing Quora.docx...
Processing iTaxi.docx...
Processing Steam.docx...
Processing Keep.docx...
Processing Pyszne.pl.docx...
Processing MyFitnessPal.docx...
Processing Zenly.docx...
Processing Cisco.docx...
Processing Apple.docx...
Processing Match.com.docx...
Processing Adobe.docx...
Processing Niantic.docx...
Processing ZipRecruiter.docx...
Processing Nike.docx...
Processing OVH.docx...
Processing Signal.docx...
Processing SHEIN.docx...
Processing Line.docx...
Processing Meta.docx...
Processing TripAdvisor.docx...
Processing Strava.docx...
Processing eToro.docx...
Processing LinkedIn.docx...
Processing Pinterest.docx...
Processing Google.docx...
Processing Toggl.docx...
Processing FineDine.docx...
Processing Baidu AI Cloud.docx...
Processing Epic Games.docx...
Processing Evernote.docx...
Processing Reddit.docx...
Processing Slack.docx...
Processing Zalando.docx...
Processing moBILET.docx...
Processing Blik.docx...
Processing Twitter.docx...
Processing ABEMA.docx...
Processing Zoom.docx...
Processing Yanosik.docx...
Processing Dropbox.docx...
Processing Tidal.docx...
Processing Krakowskie Smaki.docx...
Processing LetyShops.docx...
Processing DingTalk.docx...
Processing GG.docx...
Processing Supercell.docx...
Processing Microsoft.docx...
Processing BlaBlaCar.docx...
Processing Sympatia.pl.docx...
Processing Glovo.docx...
Processing Skyscanner.docx...
Processing Gett.docx...
Processing ALBICLA.docx...
Processing ~$adidas.docx...
Error processing ~$adidas.docx: [Errno 2] No such file or directory: './datasets/Annotated Terms of Service of 100 Online Platforms/Annotated ToS/Annotator 2/~$adidas.docx'
Processing EA.docx...
Processing Aliexpress.docx...
Processing adidas.docx...
Processing Booking.com.docx...
Processing Netflix.docx...
Processing PAYBACK.docx...
Processing Yahoo.docx...
Processing The Witcher - Monster Slayer.docx...
Processing Telegram.docx...
Processing Hotels.com.docx...
YouTube.docx: 20 comments extracted
SQUARE ENIX.docx: 41 comments extracted
Vinted.docx: 28 comments extracted
Dailymotion.docx: 24 comments extracted
MyTaxi.docx: 15 comments extracted
Pracuj.pl.docx: 20 comments extracted
Oktawave.docx: 19 comments extracted
FollowMyHealth.docx: 17 comments extracted
Spotify.docx: 63 comments extracted
Badoo.docx: 34 comments extracted
Allegro.docx: 29 comments extracted
Snapchat.docx: 37 comments extracted
Tinder.docx: 32 comments extracted
Viber.docx: 34 comments extracted
Twitch.docx: 50 comments extracted
MultiSport.docx: 11 comments extracted
EliteSingles.docx: 11 comments extracted
Uber.docx: 24 comments extracted
trivago.docx: 11 comments extracted
Bolt.docx: 26 comments extracted
Wolt.docx: 13 comments extracted
Ubisoft.docx: 30 comments extracted
vod.mdag.pl.docx: 17 comments extracted
ZnanyLekarz.docx: 20 comments extracted
iCloud.docx: 31 comments extracted
HBO GO.docx: 23 comments extracted
KAYAK.docx: 24 comments extracted
PayPal.docx: 39 comments extracted
DoorDash.docx: 31 comments extracted
PayPay.docx: 18 comments extracted
Discord.docx: 39 comments extracted
Amazon.docx: 23 comments extracted
Maya.docx: 22 comments extracted
TikTok.docx: 32 comments extracted
Lyft.docx: 33 comments extracted
Sleep Cycle.docx: 6 comments extracted
Crypto.com.docx: 78 comments extracted
Quora.docx: 30 comments extracted
iTaxi.docx: 15 comments extracted
Steam.docx: 28 comments extracted
Keep.docx: 27 comments extracted
Pyszne.pl.docx: 4 comments extracted
MyFitnessPal.docx: 46 comments extracted
Zenly.docx: 17 comments extracted
Cisco.docx: 28 comments extracted
Apple.docx: 27 comments extracted
Match.com.docx: 35 comments extracted
Adobe.docx: 36 comments extracted
Niantic.docx: 40 comments extracted
ZipRecruiter.docx: 73 comments extracted
Nike.docx: 32 comments extracted
OVH.docx: 38 comments extracted
Signal.docx: 17 comments extracted
SHEIN.docx: 34 comments extracted
Line.docx: 20 comments extracted
Meta.docx: 32 comments extracted
TripAdvisor.docx: 38 comments extracted
Strava.docx: 44 comments extracted
eToro.docx: 73 comments extracted
LinkedIn.docx: 30 comments extracted
Pinterest.docx: 37 comments extracted
Google.docx: 31 comments extracted
Toggl.docx: 30 comments extracted
FineDine.docx: 24 comments extracted
Baidu AI Cloud.docx: 41 comments extracted
Epic Games.docx: 36 comments extracted
Evernote.docx: 26 comments extracted
Reddit.docx: 31 comments extracted
Slack.docx: 24 comments extracted
Zalando.docx: 9 comments extracted
moBILET.docx: 17 comments extracted
Blik.docx: 16 comments extracted
Twitter.docx: 32 comments extracted
ABEMA.docx: 17 comments extracted
Zoom.docx: 20 comments extracted
Yanosik.docx: 11 comments extracted
Dropbox.docx: 52 comments extracted
Tidal.docx: 20 comments extracted
Krakowskie Smaki.docx: 9 comments extracted
LetyShops.docx: 34 comments extracted
DingTalk.docx: 30 comments extracted
GG.docx: 18 comments extracted
Supercell.docx: 34 comments extracted
Microsoft.docx: 50 comments extracted
BlaBlaCar.docx: 19 comments extracted
Sympatia.pl.docx: 24 comments extracted
Glovo.docx: 22 comments extracted
Skyscanner.docx: 19 comments extracted
Gett.docx: 25 comments extracted
ALBICLA.docx: 18 comments extracted
EA.docx: 29 comments extracted
Aliexpress.docx: 40 comments extracted
adidas.docx: 24 comments extracted
Booking.com.docx: 28 comments extracted
Netflix.docx: 13 comments extracted
PAYBACK.docx: 17 comments extracted
Yahoo.docx: 30 comments extracted
The Witcher - Monster Slayer.docx: 52 comments extracted
Telegram.docx: 2 comments extracted
Hotels.com.docx: 28 comments extracted

In [38]:
# Flatten the dictionary into a list of rows
rows = []
for filename, comments in comments_dict.items():
    for comment in comments:
        rows.append({
            'filename': filename,
            'comment_id': comment['id'],
            'author': comment['author'],
            'comment': comment['comment'],
            'referenced_text': comment['referenced_text']
        })

# Create DataFrame and export to CSV
comments_export_df = pd.DataFrame(rows)
comments_export_df.to_csv('annotated_tos_comments_2.csv', index=False)

## Extracted Comments Data Preprocessing

In [14]:
tos_comments_df = pd.read_csv('annotated_tos_comments.csv')
tos_comments_df.head()

,filename,comment_id,author,comment,referenced_text
0,YouTube.docx,0,Autor,docu 1-3,Your use of the Service is subject to these te...
1,YouTube.docx,1,Autor,uncle,as permitted by applicable law;
2,YouTube.docx,2,Autor,docu 4,run contests on or through the Service that do...
3,YouTube.docx,3,Autor,serv_chg 0,YouTube is constantly changing and improving t...
4,YouTube.docx,4,Autor,uncle,operability issues. We’ll also provide you wit...

Remove `.docx` extension and rename column name.

In [18]:
tos_comments_df['filename'] = tos_comments_df['filename'].str.replace('.docx', '', regex=False)
tos_comments_df = tos_comments_df.rename(columns={'filename': 'company'})

How many comments per company ToS?

In [19]:
tos_comments_df['company'].value_counts()

company
ZipRecruiter                    76
Viber                           65
MyFitnessPal                    62
Baidu AI Cloud                  59
The Witcher - Monster Slayer    59
                                ..
Pyszne.pl                       12
Krakowskie Smaki                10
Sleep Cycle                      5
Zalando                          3
Telegram                         2
Name: count, Length: 99, dtype: int64

How many of each type of variable classification?

In [20]:
tos_comments_df['comment'].value_counts()

comment
uncle                                                                     146
what                                                                      126
contr_chg -1                                                               98
ltd -1                                                                     94
serv_chg -1                                                                87
                                                                         ...
pato; infringing Art. 61 of the Polish Civil Code                           1
serv_chg -1; -1 as “reasons include, without limitation”                    1
which ones                                                                  1
pato 1; directly infringing Article 19(1)(c) of the Directive 2019/770      1
ltd _cap -1                                                                 1
Name: count, Length: 351, dtype: int64

Some comments have more than one evaluation in them (example below). Split up every grouped comment and create individual rows for each classification.

In [24]:
tos_comments_df[tos_comments_df['comment'] == 'cnt_modr 0’; disc -1; acc_sus 0; acc_del 0']

,company,comment_id,author,comment,referenced_text
2180,Epic Games,39,Autor,cnt_modr 0’; disc -1; acc_sus 0; acc_del 0,Epic may also at its sole discretion limit acc...

List all the possible variable classifications defined from Palka et al. (2023).

In [32]:
variable_classifications = {
    # Evaluative variables
    "ltd": "Limitation of company's liability",
    "ltd_cap": "Maximal threshold of company's liability", 
    "period": "Limitation period",
    "as_is": "No promises",
    "indemn": "Indemnification clause",
    "c_law": "Choice of law other than user's domicile",
    "c_forum": "Choice of forum other than user's domicile",
    "arb": "Mandatory arbitration",
    "class": "Class action waiver",
    "contr_chg": "Unilateral change of contract",
    "price_chg": "Unilateral change of future prices",
    "serv_chg": "Unilateral change of service by the company",
    "acc_del": "Account deletion and unilateral termination of contract by the company",
    "transfer": "Transfer of contractual rights to another subject",
    "cnt_del": "User content deletion",
    "acc_sus": "Account suspension",
    "recom": "Main parameters used in recommender systems",
    "com_sys": "Internal complaint-handling system",
    "cnt_retr": "Retrieval of digital content by the user",
    "IP": "Excessive user content IP license",
    "discret": "Discretional power to interpret the ToS",
    "interpret": "General interpretation clause",
    "sever": "Severability clauses",
    "suggest": "Right to incorporate user's feedback or suggestions without compensation",
    
    # Count variables
    "uncle": "Unclear law clause",
    "docu": "Other documents",
    
    # Pull-out text variables
    "core": "Promises and obligations",
    "what": "Description of the service",
    
    # Metadata
    "name": "Name of the service",
    "url": "ToS URL",
    "date": "Date effective",
    "lang": "ToS Language",
    "sector": "Service sector",
    "word_cnt": "Number of words",
    "hq": "Company's headquarter",
    "hq_cat": "Headquarter category",
    "public": "Publicly listed",
    "paid": "Paid or free services"
}

For rows with multiple classifications, split them by semicolon then create new rows. If the comment does not contain one of the above variable classifications, then remove it.

In [33]:
new_rows = []

for _, row in tos_comments_df.iterrows():
    classifications = [c.strip() for c in str(row['comment']).split(';') if c.strip()]
    for classification in classifications:
        if any(code in classification.lower() for code in variable_classifications.keys()):
            new_row = row.copy()
            new_row['comment'] = classification.lower()
            new_rows.append(new_row)

tos_comments_df = pd.DataFrame(new_rows)
tos_comments_df['comment'].value_counts()

comment
acc_del 0                                                                                                                  185
uncle                                                                                                                      147
acc_sus 0                                                                                                                  142
what                                                                                                                       129
ltd -1                                                                                                                     107
                                                                                                                          ...
each party shall be entitled to transfer all or part of the contract to its affiliates without the consumer’s agreement      1
-1 as (5) allows the service provider to perform such actions arbitrarily                                                    1
docu 6-16                                                                                                                    1
arbitration requirement applies to all consumers outside of eu                                                               1
ltd _cap -1                                                                                                                  1
Name: count, Length: 128, dtype: int64

end of v1 (for now). trying out other datasets and topics first.