# 06 — SaulLM Investigation: fixing the "neutral-on-everything" collapse

`adrienbrault/saul-instruct-v1:Q8_0` scored **topic-macro-F1 0.136 / risk-macro-F1 0.213**
in `05_generative_llm_runs.ipynb`. Inspecting its raw output (`§7.2.2` of the
changelog) found **four** concrete failure modes, not one vague "small model is weak":

1. `risk = neutral` on **all 2,656/2,656** rows — zero variance, majority-class collapse.
2. Topic over-generation — median 6 but p75 34, **max 188** on a 42-topic taxonomy (carpet-bombing).
3. Hallucinated labels — invents `data_retention`, `data_*` ids that aren't in the taxonomy (→ 7,440 dropped).
4. Repetition looping that survives the `num_predict=768` cap.

**Root cause:** Ollama serves this model with a **ChatML** template (`<|im_start|>`),
but Saul-Instruct-v1 is a **Mistral-7B-Instruct** finetune trained on `[INST] … [/INST]`.
`<|im_start|>` are not Mistral special tokens → the model never enters instruction-following
mode. Frozen output (#1) and looping (#4) are textbook wrong-template symptoms.

This notebook tests three **cumulative** fixes, top-to-bottom, on the same small sample:

| Group | What it adds | Attacks |
|---|---|---|
| **Baseline** | Saul as shipped (ChatML) — reference on the *same* rows | — |
| **Approach A** | Correct **Mistral `[INST]` template** (rebuilt Modelfile) | #1 #2 #3 #4 (root cause) |
| **Approach B** | A **+ strict enum schema** (topics ∈ 42 ids) **+ `repeat_penalty`** | #2 #3 #4 mechanically |
| **Approach C** | B **+ two-stage** (topics-only, then risk-only on slim context) | #1 #2 (context overload) |

> **Cumulative by design:** B builds on A, C builds on B. Each group's marginal gain
> over the previous is the signal.

---
## Where results come out

Everything writes under **`generated_files/lawgic_taxonomy/evaluation_v2/generative_runs/_saul_investigation/`**:

```
_saul_investigation/
├── baseline_chatml/   raw_predictions.csv, mini_metrics.json
├── A_template/        raw_predictions.csv, mini_metrics.json, Modelfile
├── B_template_schema/         raw_predictions.csv, mini_metrics.json
├── C_template_schema_twostage/ raw_predictions.csv, mini_metrics.json
└── saul_investigation_summary.csv   ← the head-to-head table (final cell)
```

- `raw_predictions.csv` — one row/clause: `row_id, raw_json, parsed_topics, parsed_risk, parse_ok, latency_s`. **Resumable** (re-running a group skips rows already `parse_ok=True`).
- `mini_metrics.json` — per-group scores + diagnostics (risk distribution, topic-count stats, dropped labels).
- `saul_investigation_summary.csv` — baseline vs A vs B vs C, written by the last cell.

## How to run
1. **Prereqs:** `ollama serve` running; base model pulled (`ollama pull adrienbrault/saul-instruct-v1:Q8_0`). Local M1 — quit browsers (Q8_0 is 7.7 GB).
2. Run Sections 1–4 (shared setup), then each approach group in order. **`SMOKE=True` → 30 stratified rows** (default). Flip to `False` for the full 2,656-clause pass.
3. The **Summary** cell at the bottom prints and saves the comparison.

**Nothing here overwrites `05`'s published Saul row.** These are separate, clearly-labeled configs. The template fix (A/B) is a *serving-bug* fix; **C is a different *strategy*** (two-stage) and must be reported as such in the manuscript, not as a silent replacement.

## 1. Setup — corpus, split, label arrays (shared)

Identical corpus/split/label loading to `05` so the scoring is directly comparable.

In [9]:
import os, sys, json, time, subprocess
from pathlib import Path

os.environ["LAWGIC_CORPUS_VERSION"] = "v2"   # MUST precede the core import


def find_project_root(start: Path) -> Path:
    sentinel = "generated_files/lawgic_taxonomy/lawgic_multihead_wide_v2.csv"
    for c in (start, *start.parents):
        if (c / sentinel).exists():
            return c
    raise FileNotFoundError("Run this notebook from inside the lawgic repository.")


PROJECT_ROOT = find_project_root(Path.cwd().resolve())
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

import numpy as np
import pandas as pd
from dotenv import load_dotenv

import lawgic_eval_core as core

load_dotenv(PROJECT_ROOT / ".env")

core.persist_split()
corpus = core.load_corpus()
test = core.split_frames(corpus)["test"].reset_index(drop=True)
arrays = core.label_arrays(test)

TOPIC_IDS = core.TOPIC_IDS
NAME_BY_ID = core.TOPIC_NAME_BY_ID
TAXONOMY = json.loads(core.TAXONOMY_PATH.read_text(encoding="utf-8"))

assert len(TOPIC_IDS) == 42, len(TOPIC_IDS)
assert len(test) == 2656, len(test)
assert core.HARM_CLASS_NAMES == {0: "Harmful", 1: "Neutral", 2: "Fair"}
print(f"corpus={core._CORPUS_VERSION}  topics={len(TOPIC_IDS)}  test={len(test)}")

corpus=v2  topics=42  test=2656

## 2. Config — smoke switch, model tags, output dirs (shared)

**`SMOKE=True` runs `N_SMOKE=30` stratified rows.** Flip to `False` for the full 2,656.

In [10]:
# ── SMOKE control ────────────────────────────────────────────────────────────
SMOKE = False            # True: N_SMOKE stratified rows.  False: full 2,656-clause pass.
N_SMOKE = 30            # ~30 rows/approach as requested
SMOKE_SEED = 42         # fixed -> same rows across baseline/A/B/C and across reruns

# ── Decoding (same as 05; §4.4 requires greedy determinism) ──────────────────
NUM_CTX = 12288         # prevents Ollama's silent prompt truncation on local Saul
NUM_PREDICT = 768       # caps runaway generation
REPEAT_PENALTY = 1.3    # anti-loop knob, used in B and C (compatible with temp=0.0)

# ── Model tags ───────────────────────────────────────────────────────────────
SAUL_BASE = "adrienbrault/saul-instruct-v1:Q8_0"   # as-shipped (ChatML template)
SAUL_MISTRAL = "saul-instruct-v1-mistral:Q8_0"     # A: rebuilt with [INST] template (created in A.1)

# ── Output dirs ──────────────────────────────────────────────────────────────
BASE_DIR = core.EVAL_OUT_DIR / "generative_runs" / "_saul_investigation"
DIR_BASELINE = BASE_DIR / "baseline_chatml"
DIR_A = BASE_DIR / "A_template"
DIR_B = BASE_DIR / "B_template_schema"
DIR_C = BASE_DIR / "C_template_schema_twostage"
for d in (DIR_BASELINE, DIR_A, DIR_B, DIR_C):
    d.mkdir(parents=True, exist_ok=True)

# ── Risk map + pseudo-logit magnitudes (identical to 05) ─────────────────────
RISK_TO_CLASS = {"harmful": 0, "neutral": 1, "fair": 2}
DEFAULT_RISK_ON_FAILURE = "neutral"
POS_LOGIT, NEG_LOGIT = 10.0, -10.0
assert {v: k.capitalize() for k, v in RISK_TO_CLASS.items()} == core.HARM_CLASS_NAMES

print("Output base:", BASE_DIR)
print(f"SMOKE={SMOKE}  N_SMOKE={N_SMOKE}")

Output base: /Users/riki/Coding Projects/Thesis/lawgic/generated_files/lawgic_taxonomy/evaluation_v2/generative_runs/_saul_investigation
SMOKE=False  N_SMOKE=30

## 3. Shared helpers — prompts, schemas, parsing, run harness (shared)

Four groups of helpers reused by every approach:
- **Prompts:** `build_prompt` (single-prompt, full rubric — baseline/A) and the two-stage
  `build_topic_prompt` (slim taxonomy, no rubric) / `build_risk_prompt` (rubrics of matched topics only — C).
- **Schemas:** `ClausePrediction` (loose, free-string topics) and `ClausePredictionStrict` /
  `TopicsOnly` / `RiskOnly` (strict — topics constrained to the 42 real ids via an enum grammar — B/C).
- **Parsing / pseudo-logits:** identical to 05 (`+10/-10` trick so the scoring module is reused unchanged).
- **Run harness:** `run_approach` (resumable per-row CSV) + `score_and_report` (metrics + diagnostics).

In [11]:
import re
from enum import Enum
from typing import Literal
from pydantic import BaseModel, Field


# ── Taxonomy rendering: full (id+name+desc+rubric) vs slim (id+name+desc) ─────
def render_taxonomy_block(taxonomy, topic_ids, with_rubric=True):
    by_id = {t["id"]: t for t in taxonomy["topics"]}
    lines = []
    for tid in topic_ids:
        t = by_id[tid]
        lines.append(f"- id: {tid}")
        lines.append(f"  name: {t.get('name', tid)}")
        lines.append(f"  description: {(t.get('description') or '').strip()}")
        if with_rubric:
            lines.append("  risk_rubric:")
            for s in t.get("scores", []):
                lines.append(f"    - {s['label']}: {s['explanation'].strip()}")
    return "\n".join(lines)


TAXONOMY_BLOCK_FULL = render_taxonomy_block(TAXONOMY, TOPIC_IDS, with_rubric=True)
TAXONOMY_BLOCK_SLIM = render_taxonomy_block(TAXONOMY, TOPIC_IDS, with_rubric=False)

INSTRUCTION = (
    "You are a strict classifier of Terms-of-Service (ToS) clauses.\n"
    f"Below is a taxonomy of {len(TOPIC_IDS)} topics, each with a name, description "
    "and a 3-level risk rubric.\n"
    "Given the clause, return (1) every applicable topic ID from the taxonomy, and "
    "(2) a SINGLE overall risk class for the whole clause: exactly one of "
    "harmful, neutral, fair.\n"
    "Use only topic IDs that appear in the taxonomy. Return strict JSON only.\n"
)


def build_prompt(clause_text):
    """Single-prompt (baseline + A): full taxonomy inline, topics + risk in one call."""
    return (INSTRUCTION + "\nTAXONOMY:\n" + TAXONOMY_BLOCK_FULL
            + "\n\nCLAUSE:\n" + str(clause_text).strip()
            + '\n\nReturn JSON only: {"topics": ["<id>", ...], "risk": "harmful|neutral|fair"}')


# ── Two-stage prompts (C) ────────────────────────────────────────────────────
def build_topic_prompt(clause_text):
    """Stage 1: topics only, SLIM taxonomy (no rubric) -> smaller context for a 7B."""
    return ("You are a strict classifier of Terms-of-Service (ToS) clauses.\n"
            f"Below is a taxonomy of {len(TOPIC_IDS)} topics (id, name, description).\n"
            "Return every applicable topic ID for the clause. Use only IDs in the taxonomy.\n"
            "Return strict JSON only.\n"
            "\nTAXONOMY:\n" + TAXONOMY_BLOCK_SLIM
            + "\n\nCLAUSE:\n" + str(clause_text).strip()
            + '\n\nReturn JSON only: {"topics": ["<id>", ...]}')


def build_risk_prompt(clause_text, topic_ids_for_clause):
    """Stage 2: ONE risk class, context = only the matched topics' rubrics."""
    by_id = {t["id"]: t for t in TAXONOMY["topics"]}
    rl = []
    for tid in topic_ids_for_clause:
        t = by_id.get(tid)
        if not t:
            continue
        rl.append(f"- {tid} ({t.get('name', tid)}):")
        for s in t.get("scores", []):
            rl.append(f"    {s['label']}: {s['explanation'].strip()}")
    rubric = "\n".join(rl) if rl else "(no matched topics)"
    return ("You assess the overall risk of a Terms-of-Service (ToS) clause.\n"
            "Return ONE overall risk class for the whole clause: exactly one of "
            "harmful, neutral, fair.\n"
            "Relevant topic risk rubrics:\n" + rubric
            + "\n\nCLAUSE:\n" + str(clause_text).strip()
            + '\n\nReturn JSON only: {"risk": "harmful|neutral|fair"}')


# ── Output schemas ───────────────────────────────────────────────────────────
class ClausePrediction(BaseModel):                     # loose: baseline + A
    topics: list[str] = Field(default_factory=list)
    risk: Literal["harmful", "neutral", "fair"]


TopicEnum = Enum("TopicEnum", {tid: tid for tid in TOPIC_IDS}, type=str)   # 42 real ids


class ClausePredictionStrict(BaseModel):               # strict: B
    topics: list[TopicEnum] = Field(default_factory=list)
    risk: Literal["harmful", "neutral", "fair"]


class TopicsOnly(BaseModel):                           # C stage 1
    topics: list[TopicEnum] = Field(default_factory=list)


class RiskOnly(BaseModel):                             # C stage 2
    risk: Literal["harmful", "neutral", "fair"]


# ── Topic lookup + pseudo-logit builders (identical to 05) ───────────────────
def _norm(s):
    return re.sub(r"[\s_]+", " ", str(s).strip().lower())


def build_topic_lookup(topic_ids, name_by_id):
    lut = {}
    for idx, tid in enumerate(topic_ids):
        lut[_norm(tid)] = idx
        nm = name_by_id.get(tid)
        if nm:
            lut[_norm(nm)] = idx
    return lut


TOPIC_LOOKUP = build_topic_lookup(TOPIC_IDS, NAME_BY_ID)


def map_topics(pred_topics):
    idxs, dropped = [], []
    for t in (pred_topics or []):
        i = TOPIC_LOOKUP.get(_norm(t))
        (idxs.append(i) if i is not None else dropped.append(t))
    return sorted(set(idxs)), dropped


def topic_logits_row(idxs):
    row = np.full(len(TOPIC_IDS), NEG_LOGIT, dtype=np.float32)
    if idxs:
        row[idxs] = POS_LOGIT
    return row


def harm_logits_row(risk):
    row = np.full(3, NEG_LOGIT, dtype=np.float32)
    row[RISK_TO_CLASS[risk if risk in RISK_TO_CLASS else DEFAULT_RISK_ON_FAILURE]] = POS_LOGIT
    return row

In [13]:
from langchain_ollama import ChatOllama


def build_llm(model, schema=None, repeat_penalty=None):
    """One builder for every group. schema=None -> plain JSON mode (loose);
    schema=<pydantic> -> Ollama enforces its JSON schema (enum -> grammar)."""
    kw = dict(model=model, base_url="http://localhost:11434", temperature=0.0,
              num_ctx=NUM_CTX, num_predict=NUM_PREDICT)
    if repeat_penalty is not None:
        kw["repeat_penalty"] = repeat_penalty
    if schema is None:
        return ChatOllama(format="json", **kw)
    return ChatOllama(**kw).with_structured_output(schema)


def _topic_values(topics):
    # Enum members (strict schema) -> their .value; plain strings pass through.
    return [getattr(t, "value", t) for t in (topics or [])]


def predict_single(llm, clause_text):
    """One greedy pass (baseline + A + B). Never crashes -> parse_ok=False fallback."""
    t0 = time.perf_counter()
    topics, risk, raw, ok = [], DEFAULT_RISK_ON_FAILURE, "", True
    try:
        out = llm.invoke(build_prompt(clause_text))
        topics, risk, raw = _topic_values(out.topics), out.risk, out.model_dump_json()
    except Exception as e:
        ok, raw = False, f"PARSE_ERROR: {e}"[:2000]
    return {"parsed_topics": topics, "parsed_risk": risk, "raw_json": raw,
            "parse_ok": ok, "latency_s": round(time.perf_counter() - t0, 3)}


def predict_twostage(topic_llm, risk_llm, clause_text):
    """C: stage 1 topics (slim) -> stage 2 risk (rubrics of matched topics only)."""
    t0 = time.perf_counter()
    topics, risk, ok, raws = [], DEFAULT_RISK_ON_FAILURE, True, {}
    try:
        o1 = topic_llm.invoke(build_topic_prompt(clause_text))
        topics = _topic_values(o1.topics)
        raws["stage1"] = o1.model_dump_json()
    except Exception as e:
        ok = False
        raws["stage1"] = f"PARSE_ERROR: {e}"[:1000]
    try:
        idxs, _ = map_topics(topics)
        matched = [TOPIC_IDS[i] for i in idxs]
        o2 = risk_llm.invoke(build_risk_prompt(clause_text, matched))
        risk = o2.risk
        raws["stage2"] = o2.model_dump_json()
    except Exception as e:
        ok = False
        raws["stage2"] = f"PARSE_ERROR: {e}"[:1000]
    return {"parsed_topics": topics, "parsed_risk": risk, "raw_json": json.dumps(raws),
            "parse_ok": ok, "latency_s": round(time.perf_counter() - t0, 3)}

In [14]:
def _read_raw(raw_csv):
    df = pd.read_csv(raw_csv)
    df["row_id"] = df["row_id"].astype(int)
    df["parse_ok"] = df["parse_ok"].map(lambda x: str(x).strip().lower() in ("true", "1"))
    return df.drop_duplicates("row_id", keep="last")


def run_approach(out_dir, predict_fn, positions, verbose=True):
    """Resumable: append each clause to raw_predictions.csv; skip done row_ids."""
    raw_csv = out_dir / "raw_predictions.csv"
    done = set()
    if raw_csv.exists():
        prev = _read_raw(raw_csv)
        done = set(prev.loc[prev["parse_ok"], "row_id"])
    for n, p in enumerate(positions, 1):
        rid = int(test.iloc[p]["row_id"])
        if rid in done:
            continue
        rec = predict_fn(test.iloc[p]["text"])
        row = {"row_id": rid, "raw_json": rec["raw_json"],
               "parsed_topics": json.dumps(rec["parsed_topics"]),
               "parsed_risk": rec["parsed_risk"], "parse_ok": rec["parse_ok"],
               "latency_s": rec["latency_s"]}
        pd.DataFrame([row]).to_csv(raw_csv, mode="a", header=not raw_csv.exists(), index=False)
        done.add(rid)
        if verbose:
            print(f"  [{n}/{len(positions)}] row_id={rid} risk={rec['parsed_risk']} "
                  f"n_topics={len(rec['parsed_topics'])} ok={rec['parse_ok']} {rec['latency_s']}s")
    return raw_csv


def assemble_logits(raw, frame):
    by_id = raw.set_index("row_id")
    tl, hl, dropped, failures = [], [], 0, 0
    for rid in frame["row_id"].astype(int):
        rec = by_id.loc[rid]
        topics = rec["parsed_topics"]
        topics = json.loads(topics) if isinstance(topics, str) else list(topics or [])
        idxs, drops = map_topics(topics)
        dropped += len(drops)
        failures += int(not bool(rec["parse_ok"]))
        tl.append(topic_logits_row(idxs))
        hl.append(harm_logits_row(rec["parsed_risk"]))
    return np.vstack(tl), np.vstack(hl), dropped, failures


def score_and_report(name, out_dir, positions):
    """Score against the same rows + print diagnostics that target the 4 failure modes."""
    raw = _read_raw(out_dir / "raw_predictions.csv")
    frame = test.iloc[positions]
    raw = raw[raw["row_id"].isin(frame["row_id"])]
    tl, hl, dropped, failures = assemble_logits(raw, frame)
    m = core.all_metrics(tl, hl, {k: v[positions] for k, v in arrays.items()})
    n_topics = raw["parsed_topics"].map(lambda s: len(json.loads(s)) if isinstance(s, str) else 0)
    risk_counts = raw["parsed_risk"].value_counts().to_dict()
    rec = {
        "approach": name, "n": int(len(frame)),
        "topic_macro_f1": round(float(m["topic_macro_f1"]), 3),
        "topic_micro_f1": round(float(m["topic_micro_f1"]), 3),
        "risk_accuracy": round(float(m["risk_accuracy"]), 3),
        "risk_macro_f1": round(float(m["risk_macro_f1"]), 3),
        "risk_distribution": risk_counts,          # failure mode #1: want >1 class
        "n_risk_classes_used": len(risk_counts),
        "topics_median": float(n_topics.median()), # failure mode #2: want small
        "topics_max": int(n_topics.max()),
        "dropped_labels": int(dropped),            # failure mode #3: want 0
        "parse_failures": int(failures),
        "wall_min": round(float(raw["latency_s"].sum()) / 60, 2),
    }
    (out_dir / "mini_metrics.json").write_text(json.dumps(rec, indent=2))
    print(json.dumps(rec, indent=2))
    return rec

## 4. Sample selection — one fixed set of rows for every group (shared)

Stratified so all three observed risk classes appear (otherwise "risk variance" is meaningless). The **same** `POSITIONS` feed baseline/A/B/C, so the comparison is apples-to-apples.

In [15]:
def stratified_positions(n, seed):
    rng = np.random.default_rng(seed)
    harm, hmask = arrays["harm_labels"], arrays["harm_masks"].astype(bool)
    picks = []
    for cls in (0, 1, 2):                      # guarantee one of each observed class
        cand = np.where((harm == cls) & hmask)[0]
        if len(cand):
            picks.append(int(rng.choice(cand)))
    pool = np.where(hmask)[0].tolist()
    rng.shuffle(pool)
    for p in pool:
        if len(picks) >= n:
            break
        if p not in picks:
            picks.append(p)
    return picks[:n]


POSITIONS = stratified_positions(N_SMOKE, SMOKE_SEED) if SMOKE else list(range(len(test)))
RESULTS = {}   # approach name -> metrics rec (filled by each group; read by Summary)

gold = pd.Series([core.HARM_CLASS_NAMES.get(int(c)) for c in arrays["harm_labels"][POSITIONS]])
print(f"SMOKE={SMOKE}  n={len(POSITIONS)}")
print("gold risk distribution:", gold.value_counts().to_dict())

SMOKE=False  n=2656
gold risk distribution: {'Neutral': 1246, 'Harmful': 832, 'Fair': 578}

---
## Baseline — Saul as shipped (ChatML), same rows  ·  *reference point*

**Not one of the three fixes** — this reruns the broken `05` config on the *same* 30 rows
so the summary table compares like-for-like (the published `05` number is a 2,656-row
aggregate). Expect the four failure modes to reappear here: risk all-`neutral`, huge
`topics_max`, non-zero `dropped_labels`.

→ writes **`_saul_investigation/baseline_chatml/`**

In [7]:
# BASELINE  (SAUL_BASE = ChatML template, loose schema — exactly the 05 setup)
baseline_llm = build_llm(SAUL_BASE, schema=ClausePrediction)
run_approach(DIR_BASELINE, lambda txt: predict_single(baseline_llm, txt), POSITIONS)
RESULTS["baseline_chatml"] = score_and_report("baseline_chatml", DIR_BASELINE, POSITIONS)

  [1/30] row_id=3300 risk=neutral n_topics=7 ok=True 45.127s
  [2/30] row_id=19775 risk=neutral n_topics=114 ok=True 60.525s
  [3/30] row_id=17804 risk=neutral n_topics=1 ok=True 2.821s
  [4/30] row_id=7551 risk=neutral n_topics=2 ok=True 3.573s
  [5/30] row_id=21002 risk=neutral n_topics=1 ok=True 2.549s
  [6/30] row_id=25746 risk=neutral n_topics=3 ok=True 3.361s
  [7/30] row_id=2304 risk=neutral n_topics=3 ok=True 2.93s
  [8/30] row_id=13324 risk=neutral n_topics=38 ok=True 15.726s
  [9/30] row_id=1142 risk=neutral n_topics=1 ok=True 2.071s
  [10/30] row_id=14768 risk=neutral n_topics=29 ok=True 11.716s
  [11/30] row_id=17287 risk=neutral n_topics=2 ok=True 2.803s
  [12/30] row_id=15651 risk=neutral n_topics=4 ok=True 2.549s
  [13/30] row_id=9806 risk=neutral n_topics=1 ok=True 2.602s
  [14/30] row_id=23139 risk=neutral n_topics=111 ok=True 44.428s
  [15/30] row_id=3994 risk=neutral n_topics=1 ok=True 2.702s
  [16/30] row_id=22281 risk=neutral n_topics=16 ok=True 6.387s
  [17/30] row_id=5361 risk=neutral n_topics=1 ok=True 2.038s
  [18/30] row_id=10362 risk=neutral n_topics=5 ok=True 3.235s
  [19/30] row_id=19375 risk=neutral n_topics=5 ok=True 3.06s
  [20/30] row_id=4365 risk=neutral n_topics=6 ok=True 3.441s
  [21/30] row_id=19502 risk=neutral n_topics=39 ok=True 20.394s
  [22/30] row_id=112 risk=neutral n_topics=4 ok=True 3.821s
  [23/30] row_id=21405 risk=neutral n_topics=12 ok=True 5.997s
  [24/30] row_id=21428 risk=neutral n_topics=38 ok=True 16.995s
  [25/30] row_id=3928 risk=neutral n_topics=10 ok=True 5.205s
  [26/30] row_id=26296 risk=neutral n_topics=3 ok=True 3.056s
  [27/30] row_id=21339 risk=neutral n_topics=1 ok=True 2.233s
  [28/30] row_id=359 risk=neutral n_topics=29 ok=True 11.551s
  [29/30] row_id=25377 risk=neutral n_topics=3 ok=True 2.792s
  [30/30] row_id=21668 risk=neutral n_topics=7 ok=True 4.084s
{
  "approach": "baseline_chatml",
  "n": 30,
  "topic_macro_f1": 0.102,
  "topic_micro_f1": 0.123,
  "risk_accuracy": 0.5,
  "risk_macro_f1": 0.222,
  "risk_distribution": {
    "neutral": 30
  },
  "n_risk_classes_used": 1,
  "topics_median": 4.5,
  "topics_max": 114,
  "dropped_labels": 50,
  "parse_failures": 0,
  "wall_min": 5.0
}

---
# ══════════════ APPROACH A — Mistral `[INST]` template ══════════════

**The root-cause fix.** Rebuild the model with the correct Mistral instruct template
instead of Ollama's bundled ChatML. **Same loose schema and same single prompt as the
baseline** — so any change here is attributable to the template alone.

- **A.1** — write a `Modelfile` and `ollama create` the `[INST]`-templated model.
- **A.2** — run the 30 rows and score.

→ writes **`_saul_investigation/A_template/`** (incl. the `Modelfile` used)

### A.1 — Rebuild Saul with the `[INST]` template

Idempotent: safe to re-run. Verifies the new template took effect.

In [16]:
# A.1 — create SAUL_MISTRAL from SAUL_BASE with Mistral's [INST] template.
MODELFILE = (
    "FROM __BASE__\n"
    'TEMPLATE "[INST] {{ .Prompt }} [/INST]"\n'
    'PARAMETER stop "</s>"\n'
    'PARAMETER stop "[INST]"\n'
).replace("__BASE__", SAUL_BASE)

mf_path = DIR_A / "Modelfile"
mf_path.write_text(MODELFILE)

res = subprocess.run(["ollama", "create", SAUL_MISTRAL, "-f", str(mf_path)],
                     capture_output=True, text=True)
print((res.stdout or res.stderr).strip()[-600:])
assert res.returncode == 0, f"ollama create failed: {res.stderr[-500:]}"

# Verify the template actually changed to [INST] (not ChatML).
shown = subprocess.run(["ollama", "show", SAUL_MISTRAL, "--template"],
                       capture_output=True, text=True).stdout
print("\n--- active template ---\n" + shown.strip())
assert "[INST]" in shown and "im_start" not in shown, "template did not switch to [INST]"
print(f"\nOK: {SAUL_MISTRAL} now serves the [INST] template.")

gathering model components
using existing layer sha256:2e46e1dd849eeaa2fd4996b1c6e035a78b31b9510658fb42526c6745d872e6be
using existing layer sha256:68693db5eb3e0501c644080a545730fc93d2ca2dfddf03633642b99f3a1f0e3c
using existing layer sha256:3307d216763acfa1df163d6ddf7d764a13755b1c0040b511246b3d9fd3c00fad
writing manifest
success

--- active template ---
[INST] {{ .Prompt }} [/INST]

OK: saul-instruct-v1-mistral:Q8_0 now serves the [INST] template.

### A.2 — Run + score Approach A

In [9]:
a_llm = build_llm(SAUL_MISTRAL, schema=ClausePrediction)   # [INST] template, loose schema
run_approach(DIR_A, lambda txt: predict_single(a_llm, txt), POSITIONS)
RESULTS["A_template"] = score_and_report("A_template", DIR_A, POSITIONS)

  [1/30] row_id=3300 risk=neutral n_topics=0 ok=True 30.945s
  [2/30] row_id=19775 risk=harmful n_topics=0 ok=True 1.077s
  [3/30] row_id=17804 risk=neutral n_topics=0 ok=True 0.951s
  [4/30] row_id=7551 risk=neutral n_topics=0 ok=True 1.243s
  [5/30] row_id=21002 risk=neutral n_topics=0 ok=True 1.096s
  [6/30] row_id=25746 risk=neutral n_topics=0 ok=True 1.214s
  [7/30] row_id=2304 risk=neutral n_topics=0 ok=True 1.062s
  [8/30] row_id=13324 risk=neutral n_topics=0 ok=True 1.082s
  [9/30] row_id=1142 risk=neutral n_topics=0 ok=True 0.886s
  [10/30] row_id=14768 risk=neutral n_topics=0 ok=True 0.928s
  [11/30] row_id=17287 risk=neutral n_topics=0 ok=True 1.373s
  [12/30] row_id=15651 risk=neutral n_topics=0 ok=True 0.905s
  [13/30] row_id=9806 risk=neutral n_topics=0 ok=True 1.254s
  [14/30] row_id=23139 risk=neutral n_topics=0 ok=True 1.266s
  [15/30] row_id=3994 risk=harmful n_topics=0 ok=True 1.439s
  [16/30] row_id=22281 risk=neutral n_topics=0 ok=True 0.901s
  [17/30] row_id=5361 risk=neutral n_topics=0 ok=True 1.049s
  [18/30] row_id=10362 risk=neutral n_topics=0 ok=True 1.45s
  [19/30] row_id=19375 risk=neutral n_topics=0 ok=True 1.196s
  [20/30] row_id=4365 risk=fair n_topics=0 ok=True 1.318s
  [21/30] row_id=19502 risk=neutral n_topics=0 ok=True 1.057s
  [22/30] row_id=112 risk=neutral n_topics=0 ok=True 1.044s
  [23/30] row_id=21405 risk=neutral n_topics=0 ok=True 0.877s
  [24/30] row_id=21428 risk=neutral n_topics=0 ok=True 0.875s
  [25/30] row_id=3928 risk=neutral n_topics=0 ok=True 0.838s
  [26/30] row_id=26296 risk=neutral n_topics=0 ok=True 1.234s
  [27/30] row_id=21339 risk=neutral n_topics=0 ok=True 1.344s
  [28/30] row_id=359 risk=neutral n_topics=0 ok=True 0.874s
  [29/30] row_id=25377 risk=neutral n_topics=0 ok=True 1.368s
  [30/30] row_id=21668 risk=neutral n_topics=0 ok=True 1.001s
{
  "approach": "A_template",
  "n": 30,
  "topic_macro_f1": 0.0,
  "topic_micro_f1": 0.0,
  "risk_accuracy": 0.467,
  "risk_macro_f1": 0.373,
  "risk_distribution": {
    "neutral": 27,
    "harmful": 2,
    "fair": 1
  },
  "n_risk_classes_used": 3,
  "topics_median": 0.0,
  "topics_max": 0,
  "dropped_labels": 0,
  "parse_failures": 0,
  "wall_min": 1.05
}

---
# ══════════════ APPROACH B — A + enum grammar + `repeat_penalty` ══════════════

Builds on A. Adds two mechanical guards:
- **Strict enum schema** (`ClausePredictionStrict`): `topics` items must be one of the
  **42 real ids** → Ollama compiles this to a grammar, making hallucinated `data_*`
  labels (failure #3) *impossible to emit* and bounding over-generation (failure #2).
- **`repeat_penalty=1.3`** → directly discourages the degenerate repetition loop (failure #4).

Same `[INST]` model (`SAUL_MISTRAL`) and same single prompt as A.

→ writes **`_saul_investigation/B_template_schema/`**

In [10]:
b_llm = build_llm(SAUL_MISTRAL, schema=ClausePredictionStrict, repeat_penalty=REPEAT_PENALTY)
run_approach(DIR_B, lambda txt: predict_single(b_llm, txt), POSITIONS)
RESULTS["B_template_schema"] = score_and_report("B_template_schema", DIR_B, POSITIONS)

  [1/30] row_id=3300 risk=neutral n_topics=1 ok=True 1.426s
  [2/30] row_id=19775 risk=neutral n_topics=1 ok=True 1.551s
  [3/30] row_id=17804 risk=neutral n_topics=1 ok=True 1.644s
  [4/30] row_id=7551 risk=neutral n_topics=1 ok=True 1.833s
  [5/30] row_id=21002 risk=neutral n_topics=1 ok=True 1.521s
  [6/30] row_id=25746 risk=neutral n_topics=1 ok=True 1.72s
  [7/30] row_id=2304 risk=neutral n_topics=1 ok=True 1.61s
  [8/30] row_id=13324 risk=neutral n_topics=1 ok=True 1.715s
  [9/30] row_id=1142 risk=neutral n_topics=1 ok=True 1.651s
  [10/30] row_id=14768 risk=neutral n_topics=1 ok=True 1.774s
  [11/30] row_id=17287 risk=neutral n_topics=1 ok=True 2.347s
  [12/30] row_id=15651 risk=neutral n_topics=1 ok=True 1.602s
  [13/30] row_id=9806 risk=neutral n_topics=1 ok=True 1.97s
  [14/30] row_id=23139 risk=neutral n_topics=1 ok=True 2.017s
  [15/30] row_id=3994 risk=neutral n_topics=1 ok=True 2.006s
  [16/30] row_id=22281 risk=neutral n_topics=1 ok=True 2.536s
  [17/30] row_id=5361 risk=neutral n_topics=1 ok=True 1.797s
  [18/30] row_id=10362 risk=neutral n_topics=1 ok=True 10.292s
  [19/30] row_id=19375 risk=neutral n_topics=1 ok=True 3.047s
  [20/30] row_id=4365 risk=neutral n_topics=1 ok=True 1.893s
  [21/30] row_id=19502 risk=neutral n_topics=1 ok=True 26.601s
  [22/30] row_id=112 risk=neutral n_topics=1 ok=True 2.636s
  [23/30] row_id=21405 risk=neutral n_topics=1 ok=True 1.747s
  [24/30] row_id=21428 risk=neutral n_topics=1 ok=True 1.511s
  [25/30] row_id=3928 risk=neutral n_topics=1 ok=True 9.289s
  [26/30] row_id=26296 risk=neutral n_topics=1 ok=True 3.586s
  [27/30] row_id=21339 risk=neutral n_topics=1 ok=True 1.735s
  [28/30] row_id=359 risk=neutral n_topics=1 ok=True 9.833s
  [29/30] row_id=25377 risk=neutral n_topics=1 ok=True 2.268s
  [30/30] row_id=21668 risk=neutral n_topics=1 ok=True 1.544s
{
  "approach": "B_template_schema",
  "n": 30,
  "topic_macro_f1": 0.112,
  "topic_micro_f1": 0.261,
  "risk_accuracy": 0.5,
  "risk_macro_f1": 0.222,
  "risk_distribution": {
    "neutral": 30
  },
  "n_risk_classes_used": 1,
  "topics_median": 1.0,
  "topics_max": 1,
  "dropped_labels": 0,
  "parse_failures": 0,
  "wall_min": 1.78
}

---
# ══════════════ APPROACH C — B + two-stage (topics → risk) ══════════════

Builds on B, and additionally **shrinks the per-call context** — the hypothesis that a
6.5k-token single prompt overloads a 7B model:
- **Stage 1** (`build_topic_prompt`, `TopicsOnly`): topics only, **slim** taxonomy
  (id+name+description, no rubric) → much smaller prompt.
- **Stage 2** (`build_risk_prompt`, `RiskOnly`): the single risk class, context = **only
  the matched topics' rubrics**, not all 42. Directly targets the frozen-`neutral` (failure #1).

Both stages keep the enum grammar + `repeat_penalty`. `latency_s` sums both stages.

> **Manuscript note:** C is a **different strategy** (two-stage), not just a serving fix —
> report it as its own config, never as a drop-in replacement of the single-prompt Saul row.

→ writes **`_saul_investigation/C_template_schema_twostage/`**

In [11]:
c_topic_llm = build_llm(SAUL_MISTRAL, schema=TopicsOnly, repeat_penalty=REPEAT_PENALTY)
c_risk_llm = build_llm(SAUL_MISTRAL, schema=RiskOnly, repeat_penalty=REPEAT_PENALTY)
run_approach(DIR_C, lambda txt: predict_twostage(c_topic_llm, c_risk_llm, txt), POSITIONS)
RESULTS["C_template_schema_twostage"] = score_and_report("C_template_schema_twostage", DIR_C, POSITIONS)

  [1/30] row_id=3300 risk=neutral n_topics=1 ok=True 19.959s
  [2/30] row_id=19775 risk=harmful n_topics=2 ok=True 4.728s
  [3/30] row_id=17804 risk=neutral n_topics=1 ok=True 2.853s
  [4/30] row_id=7551 risk=neutral n_topics=1 ok=True 3.056s
  [5/30] row_id=21002 risk=neutral n_topics=1 ok=True 2.851s
  [6/30] row_id=25746 risk=neutral n_topics=1 ok=True 2.982s
  [7/30] row_id=2304 risk=neutral n_topics=2 ok=True 2.606s
  [8/30] row_id=13324 risk=harmful n_topics=2 ok=True 3.003s
  [9/30] row_id=1142 risk=harmful n_topics=1 ok=True 1.753s
  [10/30] row_id=14768 risk=neutral n_topics=0 ok=True 1.429s
  [11/30] row_id=17287 risk=neutral n_topics=1 ok=True 2.493s
  [12/30] row_id=15651 risk=neutral n_topics=2 ok=True 2.487s
  [13/30] row_id=9806 risk=harmful n_topics=1 ok=True 2.675s
  [14/30] row_id=23139 risk=neutral n_topics=1 ok=True 2.905s
  [15/30] row_id=3994 risk=harmful n_topics=1 ok=True 3.191s
  [16/30] row_id=22281 risk=neutral n_topics=1 ok=True 2.377s
  [17/30] row_id=5361 risk=harmful n_topics=1 ok=True 1.84s
  [18/30] row_id=10362 risk=neutral n_topics=2 ok=True 3.205s
  [19/30] row_id=19375 risk=neutral n_topics=2 ok=True 2.555s
  [20/30] row_id=4365 risk=neutral n_topics=1 ok=True 1.709s
  [21/30] row_id=19502 risk=neutral n_topics=2 ok=True 2.647s
  [22/30] row_id=112 risk=neutral n_topics=1 ok=True 3.106s
  [23/30] row_id=21405 risk=neutral n_topics=1 ok=True 2.334s
  [24/30] row_id=21428 risk=neutral n_topics=2 ok=True 2.429s
  [25/30] row_id=3928 risk=neutral n_topics=2 ok=True 2.914s
  [26/30] row_id=26296 risk=harmful n_topics=1 ok=True 2.165s
  [27/30] row_id=21339 risk=neutral n_topics=1 ok=True 2.429s
  [28/30] row_id=359 risk=neutral n_topics=1 ok=True 2.233s
  [29/30] row_id=25377 risk=harmful n_topics=1 ok=True 2.954s
  [30/30] row_id=21668 risk=neutral n_topics=2 ok=True 2.684s
{
  "approach": "C_template_schema_twostage",
  "n": 30,
  "topic_macro_f1": 0.116,
  "topic_micro_f1": 0.282,
  "risk_accuracy": 0.5,
  "risk_macro_f1": 0.332,
  "risk_distribution": {
    "neutral": 22,
    "harmful": 8
  },
  "n_risk_classes_used": 2,
  "topics_median": 1.0,
  "topics_max": 2,
  "dropped_labels": 0,
  "parse_failures": 0,
  "wall_min": 1.61
}

---
# ══════════════ SUMMARY — baseline vs A vs B vs C ══════════════

Head-to-head on the **same rows**. Watch four columns against the failure modes:
`n_risk_classes_used` (#1, want >1 — the "neutral on everything" fix), `topics_max`
(#2, want small), `dropped_labels` (#3, want 0), and whether the loop is gone (reflected
in `topics_max` + `wall_min`).

→ writes **`_saul_investigation/saul_investigation_summary.csv`**

In [12]:
order = ["baseline_chatml", "A_template", "B_template_schema", "C_template_schema_twostage"]
cols = ["approach", "n", "topic_macro_f1", "topic_micro_f1", "risk_accuracy",
        "risk_macro_f1", "n_risk_classes_used", "topics_median", "topics_max",
        "dropped_labels", "wall_min"]
summary = pd.DataFrame([RESULTS[k] for k in order if k in RESULTS])[cols]
display(summary)

out_csv = BASE_DIR / "saul_investigation_summary.csv"
summary.to_csv(out_csv, index=False)
print("wrote", out_csv)
print("\nReference — published full 2,656-row run (ChatML, 05): "
      "topic_macro_f1=0.136  risk_macro_f1=0.213  dropped=7440  (risk=neutral on all rows)")

,approach,n,topic_macro_f1,topic_micro_f1,risk_accuracy,risk_macro_f1,n_risk_classes_used,topics_median,topics_max,dropped_labels,wall_min
0,baseline_chatml,30,0.102,0.123,0.500,0.222,1,4.5,114,50,5.00
1,A_template,30,0.000,0.000,0.467,0.373,3,0.0,0,0,1.05
2,B_template_schema,30,0.112,0.261,0.500,0.222,1,1.0,1,0,1.78
3,C_template_schema_twostage,30,0.116,0.282,0.500,0.332,2,1.0,2,0,1.61

wrote /Users/riki/Coding Projects/Thesis/lawgic/generated_files/lawgic_taxonomy/evaluation_v2/generative_runs/_saul_investigation/saul_investigation_summary.csv

Reference — published full 2,656-row run (ChatML, 05): topic_macro_f1=0.136  risk_macro_f1=0.213  dropped=7440  (risk=neutral on all rows)

---
# ══════════════ APPROACH D — C + topic-recall nudge ══════════════

**Motivation (from the smoke):** C fixed risk + well-formedness, but stage 1 collapsed to
**1–2 topics/clause** — the enum grammar + a 7B emit the *minimal* satisfying list, so topic
**recall** (and macro-F1) stayed low even though precision was clean. D changes **only the
stage-1 prompt wording** to explicitly ask for *every* applicable topic ("most clauses match
2–6, don't return just one"). Everything else is identical to C (same `[INST]` model, enum
grammar, `repeat_penalty`, two-stage, same risk stage).

Isolates the wording effect: **D vs C** = the marginal value of the recall nudge.

→ writes **`_saul_investigation/D_twostage_recall/`** and a `saul_recall_nudge_compare.csv`

## What you need to run
1. Re-run the shared setup once if this is a fresh kernel: **§1, §2, §3, §4** (they define
   `test`, `build_llm`, `run_approach`, `score_and_report`, `POSITIONS`, `RESULTS`, `SAUL_MISTRAL`, …).
   `SAUL_MISTRAL` must already exist — if not, run **A.1** once to create it.
2. Then run the **two cells below** (D.run, then D-vs-C compare). Nothing else needs re-running;
   `RESULTS["C_template_schema_twostage"]` is reused from the C cell for the comparison, so run
   the **C cell** at least once first (or the compare cell will only show D).

### D.run — nudged stage-1 prompt, two-stage, score

In [17]:
# ── APPROACH D — C + topic-recall nudge (stage-1 wording only) ────────────────
DIR_D = BASE_DIR / "D_twostage_recall"
DIR_D.mkdir(parents=True, exist_ok=True)


def build_topic_prompt_nudge(clause_text):
    """Stage 1 + recall nudge: ask for ALL applicable topics (typically 2-6), instead of
    the single minimal one the enum grammar collapsed to in C. Slim taxonomy, as in C."""
    return ("You are a strict classifier of Terms-of-Service (ToS) clauses.\n"
            f"Below is a taxonomy of {len(TOPIC_IDS)} topics (id, name, description).\n"
            "Return EVERY applicable topic ID for the clause. Most clauses match SEVERAL "
            "topics (typically 2-6) - do NOT return just one if more apply. Include every "
            "topic the clause plausibly touches. Use only IDs in the taxonomy.\n"
            "Return strict JSON only.\n"
            "\nTAXONOMY:\n" + TAXONOMY_BLOCK_SLIM
            + "\n\nCLAUSE:\n" + str(clause_text).strip()
            + '\n\nReturn JSON only: {"topics": ["<id>", ...]}')


def predict_twostage_nudge(topic_llm, risk_llm, clause_text):
    """Same as predict_twostage but stage 1 uses the recall-nudged prompt."""
    t0 = time.perf_counter()
    topics, risk, ok, raws = [], DEFAULT_RISK_ON_FAILURE, True, {}
    try:
        o1 = topic_llm.invoke(build_topic_prompt_nudge(clause_text))
        topics = _topic_values(o1.topics)
        raws["stage1"] = o1.model_dump_json()
    except Exception as e:
        ok = False
        raws["stage1"] = f"PARSE_ERROR: {e}"[:1000]
    try:
        idxs, _ = map_topics(topics)
        matched = [TOPIC_IDS[i] for i in idxs]
        o2 = risk_llm.invoke(build_risk_prompt(clause_text, matched))
        risk = o2.risk
        raws["stage2"] = o2.model_dump_json()
    except Exception as e:
        ok = False
        raws["stage2"] = f"PARSE_ERROR: {e}"[:1000]
    return {"parsed_topics": topics, "parsed_risk": risk, "raw_json": json.dumps(raws),
            "parse_ok": ok, "latency_s": round(time.perf_counter() - t0, 3)}


d_topic_llm = build_llm(SAUL_MISTRAL, schema=TopicsOnly, repeat_penalty=REPEAT_PENALTY)
d_risk_llm = build_llm(SAUL_MISTRAL, schema=RiskOnly, repeat_penalty=REPEAT_PENALTY)
run_approach(DIR_D, lambda txt: predict_twostage_nudge(d_topic_llm, d_risk_llm, txt), POSITIONS)
RESULTS["D_twostage_recall"] = score_and_report("D_twostage_recall", DIR_D, POSITIONS)

  [1/2656] row_id=5 risk=harmful n_topics=1 ok=True 23.074s
  [2/2656] row_id=12 risk=neutral n_topics=1 ok=True 3.192s
  [3/2656] row_id=18 risk=neutral n_topics=2 ok=True 5.371s
  [4/2656] row_id=22 risk=harmful n_topics=2 ok=True 3.442s
  [5/2656] row_id=27 risk=neutral n_topics=1 ok=True 1.821s
  [6/2656] row_id=35 risk=neutral n_topics=1 ok=True 2.181s
  [7/2656] row_id=40 risk=neutral n_topics=1 ok=True 2.269s
  [8/2656] row_id=43 risk=harmful n_topics=1 ok=True 3.619s
  [9/2656] row_id=52 risk=harmful n_topics=1 ok=True 2.074s
  [10/2656] row_id=56 risk=harmful n_topics=1 ok=True 2.056s
  [11/2656] row_id=58 risk=neutral n_topics=1 ok=True 1.757s
  [12/2656] row_id=59 risk=harmful n_topics=2 ok=True 2.424s
  [13/2656] row_id=64 risk=harmful n_topics=1 ok=True 2.179s
  [14/2656] row_id=77 risk=neutral n_topics=2 ok=True 3.962s
  [15/2656] row_id=105 risk=harmful n_topics=2 ok=True 6.036s
  [16/2656] row_id=106 risk=harmful n_topics=1 ok=True 4.093s
  [17/2656] row_id=108 risk=neutral n_topics=1 ok=True 2.516s
  [19/2656] row_id=113 risk=neutral n_topics=1 ok=True 2.492s
  [20/2656] row_id=116 risk=harmful n_topics=1 ok=True 1.991s
  [21/2656] row_id=142 risk=neutral n_topics=2 ok=True 3.229s
  [22/2656] row_id=167 risk=neutral n_topics=1 ok=True 2.727s
  [23/2656] row_id=177 risk=neutral n_topics=1 ok=True 2.163s
  [24/2656] row_id=189 risk=harmful n_topics=1 ok=True 2.418s
  [25/2656] row_id=194 risk=neutral n_topics=1 ok=True 2.682s
  [26/2656] row_id=196 risk=neutral n_topics=2 ok=True 2.97s
  [27/2656] row_id=203 risk=harmful n_topics=2 ok=True 2.986s
  [28/2656] row_id=208 risk=neutral n_topics=2 ok=True 3.217s
  [29/2656] row_id=218 risk=harmful n_topics=1 ok=True 2.314s
  [30/2656] row_id=235 risk=neutral n_topics=1 ok=True 2.701s
  [31/2656] row_id=237 risk=harmful n_topics=2 ok=True 2.998s
  [32/2656] row_id=257 risk=neutral n_topics=2 ok=True 2.794s
  [33/2656] row_id=278 risk=neutral n_topics=2 ok=True 4.162s
  [34/2656] row_id=280 risk=neutral n_topics=2 ok=True 3.468s
  [35/2656] row_id=287 risk=neutral n_topics=1 ok=True 2.134s
  [36/2656] row_id=292 risk=neutral n_topics=2 ok=True 2.691s
  [37/2656] row_id=300 risk=neutral n_topics=1 ok=True 3.158s
  [38/2656] row_id=307 risk=neutral n_topics=1 ok=True 2.245s
  [39/2656] row_id=309 risk=neutral n_topics=1 ok=True 2.423s
  [40/2656] row_id=311 risk=neutral n_topics=1 ok=True 2.267s
  [41/2656] row_id=312 risk=neutral n_topics=1 ok=True 2.316s
  [42/2656] row_id=315 risk=neutral n_topics=1 ok=True 2.239s
  [43/2656] row_id=343 risk=neutral n_topics=1 ok=True 2.281s
  [44/2656] row_id=354 risk=harmful n_topics=1 ok=True 2.175s
  [45/2656] row_id=355 risk=harmful n_topics=1 ok=True 2.579s
  [47/2656] row_id=384 risk=harmful n_topics=1 ok=True 2.26s
  [48/2656] row_id=401 risk=harmful n_topics=1 ok=True 3.089s
  [49/2656] row_id=436 risk=neutral n_topics=1 ok=True 2.343s
  [50/2656] row_id=439 risk=neutral n_topics=1 ok=True 2.296s
  [51/2656] row_id=446 risk=harmful n_topics=1 ok=True 1.814s
  [52/2656] row_id=457 risk=neutral n_topics=1 ok=True 2.159s
  [53/2656] row_id=458 risk=neutral n_topics=1 ok=True 2.179s
  [54/2656] row_id=459 risk=neutral n_topics=2 ok=True 3.779s
  [55/2656] row_id=475 risk=harmful n_topics=1 ok=True 2.592s
  [56/2656] row_id=483 risk=neutral n_topics=1 ok=True 2.07s
  [57/2656] row_id=494 risk=neutral n_topics=2 ok=True 3.807s
  [58/2656] row_id=516 risk=neutral n_topics=1 ok=True 2.675s
  [59/2656] row_id=535 risk=neutral n_topics=1 ok=True 1.796s
  [60/2656] row_id=540 risk=neutral n_topics=1 ok=True 2.518s
  [61/2656] row_id=559 risk=harmful n_topics=1 ok=True 2.266s
  [62/2656] row_id=569 risk=neutral n_topics=1 ok=True 2.202s
  [63/2656] row_id=575 risk=harmful n_topics=1 ok=True 2.017s
  [64/2656] row_id=578 risk=harmful n_topics=1 ok=True 2.714s
  [65/2656] row_id=583 risk=neutral n_topics=1 ok=True 2.597s
  [66/2656] row_id=593 risk=neutral n_topics=2 ok=True 3.26s
  [67/2656] row_id=594 risk=harmful n_topics=2 ok=True 3.452s
  [68/2656] row_id=628 risk=neutral n_topics=2 ok=True 3.481s
  [69/2656] row_id=636 risk=neutral n_topics=1 ok=True 2.864s
  [70/2656] row_id=643 risk=neutral n_topics=1 ok=True 2.794s
  [71/2656] row_id=664 risk=harmful n_topics=2 ok=True 2.761s
  [72/2656] row_id=676 risk=neutral n_topics=1 ok=True 2.2s
  [73/2656] row_id=678 risk=harmful n_topics=1 ok=True 2.175s
  [74/2656] row_id=688 risk=harmful n_topics=1 ok=True 2.266s
  [75/2656] row_id=714 risk=harmful n_topics=1 ok=True 1.972s
  [76/2656] row_id=719 risk=harmful n_topics=1 ok=True 2.278s
  [77/2656] row_id=734 risk=harmful n_topics=2 ok=True 2.309s
  [78/2656] row_id=745 risk=neutral n_topics=2 ok=True 3.07s
  [79/2656] row_id=748 risk=neutral n_topics=1 ok=True 2.415s
  [80/2656] row_id=750 risk=harmful n_topics=2 ok=True 8.638s
  [81/2656] row_id=753 risk=harmful n_topics=2 ok=True 4.552s
  [82/2656] row_id=754 risk=neutral n_topics=2 ok=True 3.222s
  [83/2656] row_id=755 risk=neutral n_topics=2 ok=True 2.776s
  [84/2656] row_id=759 risk=neutral n_topics=1 ok=True 2.062s
  [85/2656] row_id=767 risk=harmful n_topics=1 ok=True 1.834s
  [86/2656] row_id=781 risk=neutral n_topics=1 ok=True 2.869s
  [87/2656] row_id=782 risk=harmful n_topics=1 ok=True 2.207s
  [88/2656] row_id=816 risk=neutral n_topics=2 ok=True 3.4s
  [89/2656] row_id=829 risk=neutral n_topics=2 ok=True 2.679s
  [90/2656] row_id=838 risk=neutral n_topics=1 ok=True 1.888s
  [91/2656] row_id=853 risk=neutral n_topics=1 ok=True 2.133s
  [92/2656] row_id=862 risk=harmful n_topics=2 ok=True 2.851s
  [93/2656] row_id=868 risk=harmful n_topics=2 ok=True 2.619s
  [94/2656] row_id=904 risk=neutral n_topics=2 ok=True 3.95s
  [95/2656] row_id=915 risk=harmful n_topics=1 ok=True 3.537s
  [96/2656] row_id=917 risk=harmful n_topics=1 ok=True 2.686s
  [97/2656] row_id=931 risk=harmful n_topics=1 ok=True 2.843s
  [98/2656] row_id=932 risk=neutral n_topics=2 ok=True 2.94s
  [99/2656] row_id=948 risk=neutral n_topics=2 ok=True 3.5s
  [100/2656] row_id=949 risk=neutral n_topics=2 ok=True 3.135s
  [101/2656] row_id=952 risk=neutral n_topics=2 ok=True 2.817s
  [102/2656] row_id=956 risk=neutral n_topics=2 ok=True 3.46s
  [103/2656] row_id=965 risk=harmful n_topics=1 ok=True 2.344s
  [104/2656] row_id=971 risk=neutral n_topics=1 ok=True 2.029s
  [105/2656] row_id=975 risk=neutral n_topics=2 ok=True 2.642s
  [106/2656] row_id=978 risk=neutral n_topics=2 ok=True 2.946s
  [107/2656] row_id=987 risk=neutral n_topics=1 ok=True 1.855s
  [108/2656] row_id=991 risk=harmful n_topics=1 ok=True 2.039s
  [109/2656] row_id=1010 risk=neutral n_topics=1 ok=True 2.468s
  [110/2656] row_id=1042 risk=neutral n_topics=1 ok=True 2.934s
  [111/2656] row_id=1062 risk=neutral n_topics=2 ok=True 2.501s
  [112/2656] row_id=1069 risk=harmful n_topics=1 ok=True 2.083s
  [113/2656] row_id=1073 risk=neutral n_topics=1 ok=True 2.277s
  [114/2656] row_id=1076 risk=neutral n_topics=2 ok=True 2.886s
  [115/2656] row_id=1084 risk=neutral n_topics=2 ok=True 2.66s
  [116/2656] row_id=1090 risk=neutral n_topics=2 ok=True 3.783s
  [117/2656] row_id=1092 risk=harmful n_topics=2 ok=True 4.016s
  [118/2656] row_id=1097 risk=harmful n_topics=2 ok=True 4.321s
  [119/2656] row_id=1104 risk=neutral n_topics=1 ok=True 2.653s
  [120/2656] row_id=1114 risk=harmful n_topics=1 ok=True 2.091s
  [121/2656] row_id=1116 risk=harmful n_topics=1 ok=True 2.625s
  [122/2656] row_id=1120 risk=harmful n_topics=1 ok=True 1.648s
  [123/2656] row_id=1129 risk=neutral n_topics=1 ok=True 2.288s
  [125/2656] row_id=1174 risk=neutral n_topics=2 ok=True 2.76s
  [126/2656] row_id=1179 risk=harmful n_topics=1 ok=True 2.072s
  [127/2656] row_id=1193 risk=neutral n_topics=1 ok=True 2.512s
  [128/2656] row_id=1197 risk=neutral n_topics=1 ok=True 2.814s
  [129/2656] row_id=1209 risk=harmful n_topics=1 ok=True 1.941s
  [130/2656] row_id=1222 risk=neutral n_topics=1 ok=True 3.201s
  [131/2656] row_id=1252 risk=neutral n_topics=1 ok=True 2.19s
  [132/2656] row_id=1253 risk=neutral n_topics=2 ok=True 3.268s
  [133/2656] row_id=1259 risk=neutral n_topics=2 ok=True 3.028s
  [134/2656] row_id=1271 risk=neutral n_topics=2 ok=True 4.206s
  [135/2656] row_id=1290 risk=neutral n_topics=1 ok=True 2.334s
  [136/2656] row_id=1292 risk=harmful n_topics=1 ok=True 3.191s
  [137/2656] row_id=1306 risk=neutral n_topics=1 ok=True 1.857s
  [138/2656] row_id=1310 risk=harmful n_topics=1 ok=True 1.923s
  [139/2656] row_id=1316 risk=harmful n_topics=1 ok=True 3.353s
  [140/2656] row_id=1325 risk=harmful n_topics=1 ok=True 2.197s
  [141/2656] row_id=1334 risk=harmful n_topics=1 ok=True 2.858s
  [142/2656] row_id=1342 risk=harmful n_topics=1 ok=True 2.29s
  [143/2656] row_id=1344 risk=harmful n_topics=2 ok=True 2.937s
  [144/2656] row_id=1345 risk=neutral n_topics=1 ok=True 2.145s
  [145/2656] row_id=1352 risk=harmful n_topics=1 ok=True 2.431s
  [146/2656] row_id=1362 risk=neutral n_topics=1 ok=True 2.297s
  [147/2656] row_id=1366 risk=neutral n_topics=1 ok=True 8.124s
  [148/2656] row_id=1370 risk=harmful n_topics=1 ok=True 3.033s
  [149/2656] row_id=1378 risk=neutral n_topics=1 ok=True 2.259s
  [150/2656] row_id=1380 risk=neutral n_topics=2 ok=True 3.428s
  [151/2656] row_id=1402 risk=harmful n_topics=1 ok=True 2.374s
  [152/2656] row_id=1424 risk=harmful n_topics=1 ok=True 3.129s
  [153/2656] row_id=1428 risk=harmful n_topics=1 ok=True 2.57s
  [154/2656] row_id=1430 risk=neutral n_topics=1 ok=True 2.512s
  [155/2656] row_id=1452 risk=harmful n_topics=1 ok=True 2.467s
  [156/2656] row_id=1455 risk=harmful n_topics=1 ok=True 2.334s
  [157/2656] row_id=1460 risk=neutral n_topics=1 ok=True 1.948s
  [158/2656] row_id=1472 risk=harmful n_topics=1 ok=True 2.5s
  [159/2656] row_id=1480 risk=neutral n_topics=2 ok=True 3.293s
  [160/2656] row_id=1486 risk=harmful n_topics=1 ok=True 2.442s
  [161/2656] row_id=1487 risk=neutral n_topics=2 ok=True 3.866s
  [162/2656] row_id=1488 risk=harmful n_topics=1 ok=True 2.089s
  [163/2656] row_id=1498 risk=harmful n_topics=2 ok=True 3.059s
  [164/2656] row_id=1522 risk=neutral n_topics=1 ok=True 2.269s
  [165/2656] row_id=1542 risk=harmful n_topics=1 ok=True 2.621s
  [166/2656] row_id=1554 risk=harmful n_topics=2 ok=True 4.677s
  [167/2656] row_id=1571 risk=harmful n_topics=1 ok=True 2.983s
  [168/2656] row_id=1579 risk=harmful n_topics=1 ok=True 3.393s
  [169/2656] row_id=1582 risk=neutral n_topics=1 ok=True 2.643s
  [170/2656] row_id=1591 risk=neutral n_topics=1 ok=True 2.659s
  [171/2656] row_id=1601 risk=neutral n_topics=1 ok=True 2.34s
  [172/2656] row_id=1606 risk=neutral n_topics=1 ok=True 2.483s
  [173/2656] row_id=1609 risk=neutral n_topics=1 ok=True 1.995s
  [174/2656] row_id=1623 risk=harmful n_topics=2 ok=True 8.238s
  [175/2656] row_id=1624 risk=neutral n_topics=1 ok=True 3.274s
  [176/2656] row_id=1628 risk=neutral n_topics=1 ok=True 2.336s
  [177/2656] row_id=1632 risk=harmful n_topics=2 ok=True 3.656s
  [178/2656] row_id=1633 risk=neutral n_topics=2 ok=True 2.963s
  [179/2656] row_id=1639 risk=neutral n_topics=1 ok=True 1.913s
  [180/2656] row_id=1645 risk=neutral n_topics=1 ok=True 2.448s
  [181/2656] row_id=1646 risk=neutral n_topics=2 ok=True 3.64s
  [182/2656] row_id=1663 risk=neutral n_topics=2 ok=True 3.48s
  [183/2656] row_id=1710 risk=harmful n_topics=1 ok=True 3.274s
  [184/2656] row_id=1717 risk=neutral n_topics=1 ok=True 2.283s
  [185/2656] row_id=1725 risk=harmful n_topics=1 ok=True 2.398s
  [186/2656] row_id=1733 risk=neutral n_topics=1 ok=True 2.051s
  [187/2656] row_id=1746 risk=neutral n_topics=1 ok=True 2.409s
  [188/2656] row_id=1769 risk=neutral n_topics=1 ok=True 2.664s
  [189/2656] row_id=1770 risk=harmful n_topics=1 ok=True 4.209s
  [190/2656] row_id=1782 risk=neutral n_topics=2 ok=True 3.807s
  [191/2656] row_id=1788 risk=neutral n_topics=1 ok=True 2.448s
  [192/2656] row_id=1804 risk=neutral n_topics=1 ok=True 2.423s
  [193/2656] row_id=1828 risk=neutral n_topics=1 ok=True 2.76s
  [194/2656] row_id=1829 risk=harmful n_topics=1 ok=True 3.103s
  [195/2656] row_id=1856 risk=harmful n_topics=1 ok=True 2.744s
  [196/2656] row_id=1862 risk=neutral n_topics=1 ok=True 2.462s
  [197/2656] row_id=1864 risk=neutral n_topics=1 ok=True 2.368s
  [198/2656] row_id=1894 risk=neutral n_topics=2 ok=True 2.729s
  [199/2656] row_id=1906 risk=neutral n_topics=1 ok=True 2.423s
  [200/2656] row_id=1909 risk=neutral n_topics=1 ok=True 2.386s
  [201/2656] row_id=1924 risk=neutral n_topics=2 ok=True 3.252s
  [202/2656] row_id=1941 risk=neutral n_topics=1 ok=True 1.955s
  [203/2656] row_id=1943 risk=neutral n_topics=1 ok=True 1.868s
  [204/2656] row_id=1972 risk=harmful n_topics=1 ok=True 2.043s
  [205/2656] row_id=1973 risk=neutral n_topics=2 ok=True 3.689s
  [206/2656] row_id=1987 risk=harmful n_topics=1 ok=True 3.567s
  [207/2656] row_id=1988 risk=neutral n_topics=1 ok=True 2.039s
  [208/2656] row_id=1998 risk=neutral n_topics=2 ok=True 2.963s
  [209/2656] row_id=2007 risk=neutral n_topics=1 ok=True 2.708s
  [210/2656] row_id=2010 risk=harmful n_topics=1 ok=True 2.429s
  [211/2656] row_id=2012 risk=harmful n_topics=1 ok=True 2.438s
  [212/2656] row_id=2018 risk=neutral n_topics=1 ok=True 2.762s
  [213/2656] row_id=2020 risk=harmful n_topics=1 ok=True 2.433s
  [214/2656] row_id=2045 risk=neutral n_topics=1 ok=True 2.621s
  [215/2656] row_id=2059 risk=neutral n_topics=1 ok=True 2.288s
  [216/2656] row_id=2070 risk=harmful n_topics=2 ok=True 3.77s
  [217/2656] row_id=2075 risk=harmful n_topics=1 ok=True 3.22s
  [218/2656] row_id=2082 risk=neutral n_topics=1 ok=True 2.713s
  [219/2656] row_id=2091 risk=neutral n_topics=2 ok=True 3.364s
  [220/2656] row_id=2092 risk=neutral n_topics=1 ok=True 2.657s
  [221/2656] row_id=2093 risk=harmful n_topics=2 ok=True 2.848s
  [222/2656] row_id=2134 risk=neutral n_topics=2 ok=True 3.199s
  [223/2656] row_id=2135 risk=neutral n_topics=2 ok=True 3.024s
  [224/2656] row_id=2140 risk=neutral n_topics=2 ok=True 2.323s
  [225/2656] row_id=2145 risk=neutral n_topics=1 ok=True 3.122s
  [226/2656] row_id=2146 risk=neutral n_topics=2 ok=True 3.231s
  [227/2656] row_id=2148 risk=harmful n_topics=1 ok=True 2.687s
  [228/2656] row_id=2149 risk=harmful n_topics=1 ok=True 2.103s
  [229/2656] row_id=2155 risk=neutral n_topics=1 ok=True 2.269s
  [230/2656] row_id=2156 risk=neutral n_topics=1 ok=True 2.303s
  [231/2656] row_id=2200 risk=neutral n_topics=1 ok=True 1.931s
  [232/2656] row_id=2201 risk=harmful n_topics=2 ok=True 3.459s
  [233/2656] row_id=2210 risk=harmful n_topics=1 ok=True 2.354s
  [234/2656] row_id=2211 risk=harmful n_topics=1 ok=True 2.073s
  [235/2656] row_id=2218 risk=harmful n_topics=1 ok=True 2.392s
  [236/2656] row_id=2225 risk=neutral n_topics=1 ok=True 1.93s
  [237/2656] row_id=2232 risk=harmful n_topics=1 ok=True 2.019s
  [238/2656] row_id=2254 risk=neutral n_topics=1 ok=True 2.476s
  [239/2656] row_id=2262 risk=harmful n_topics=1 ok=True 3.873s
  [240/2656] row_id=2276 risk=harmful n_topics=1 ok=True 3.337s
  [241/2656] row_id=2280 risk=neutral n_topics=1 ok=True 2.787s
  [242/2656] row_id=2302 risk=neutral n_topics=1 ok=True 2.511s
  [244/2656] row_id=2309 risk=neutral n_topics=1 ok=True 2.364s
  [245/2656] row_id=2313 risk=neutral n_topics=2 ok=True 2.581s
  [246/2656] row_id=2324 risk=neutral n_topics=1 ok=True 2.35s
  [247/2656] row_id=2325 risk=neutral n_topics=2 ok=True 3.186s
  [248/2656] row_id=2326 risk=harmful n_topics=1 ok=True 2.311s
  [249/2656] row_id=2334 risk=neutral n_topics=1 ok=True 1.863s
  [250/2656] row_id=2355 risk=harmful n_topics=1 ok=True 2.931s
  [251/2656] row_id=2358 risk=neutral n_topics=1 ok=True 2.11s
  [252/2656] row_id=2362 risk=harmful n_topics=1 ok=True 1.924s
  [253/2656] row_id=2375 risk=harmful n_topics=1 ok=True 3.425s
  [254/2656] row_id=2390 risk=harmful n_topics=1 ok=True 2.69s
  [255/2656] row_id=2393 risk=harmful n_topics=1 ok=True 2.26s
  [256/2656] row_id=2414 risk=neutral n_topics=1 ok=True 2.151s
  [257/2656] row_id=2466 risk=neutral n_topics=1 ok=True 2.02s
  [258/2656] row_id=2497 risk=neutral n_topics=1 ok=True 2.194s
  [259/2656] row_id=2500 risk=neutral n_topics=1 ok=True 2.107s
  [260/2656] row_id=2503 risk=harmful n_topics=1 ok=True 2.195s
  [261/2656] row_id=2509 risk=neutral n_topics=1 ok=True 3.098s
  [262/2656] row_id=2537 risk=neutral n_topics=1 ok=True 2.318s
  [263/2656] row_id=2544 risk=neutral n_topics=1 ok=True 2.34s
  [264/2656] row_id=2550 risk=harmful n_topics=1 ok=True 2.461s
  [265/2656] row_id=2552 risk=neutral n_topics=1 ok=True 2.228s
  [266/2656] row_id=2553 risk=harmful n_topics=1 ok=True 2.33s
  [267/2656] row_id=2557 risk=neutral n_topics=1 ok=True 2.183s
  [268/2656] row_id=2558 risk=neutral n_topics=1 ok=True 2.416s
  [269/2656] row_id=2579 risk=harmful n_topics=1 ok=True 2.507s
  [270/2656] row_id=2616 risk=neutral n_topics=2 ok=True 2.691s
  [271/2656] row_id=2623 risk=neutral n_topics=1 ok=True 2.809s
  [272/2656] row_id=2651 risk=neutral n_topics=1 ok=True 1.84s
  [273/2656] row_id=2684 risk=harmful n_topics=1 ok=True 2.424s
  [274/2656] row_id=2687 risk=neutral n_topics=1 ok=True 1.918s
  [275/2656] row_id=2692 risk=neutral n_topics=2 ok=True 2.653s
  [276/2656] row_id=2700 risk=neutral n_topics=2 ok=True 3.363s
  [277/2656] row_id=2702 risk=neutral n_topics=1 ok=True 2.561s
  [278/2656] row_id=2705 risk=neutral n_topics=1 ok=True 2.052s
  [279/2656] row_id=2709 risk=neutral n_topics=1 ok=True 2.459s
  [280/2656] row_id=2711 risk=neutral n_topics=2 ok=True 3.13s
  [281/2656] row_id=2714 risk=neutral n_topics=1 ok=True 2.223s
  [282/2656] row_id=2720 risk=harmful n_topics=1 ok=True 2.68s
  [283/2656] row_id=2727 risk=neutral n_topics=1 ok=True 2.239s
  [284/2656] row_id=2732 risk=neutral n_topics=2 ok=True 3.208s
  [285/2656] row_id=2738 risk=harmful n_topics=2 ok=True 2.815s
  [286/2656] row_id=2746 risk=neutral n_topics=2 ok=True 3.118s
  [287/2656] row_id=2751 risk=harmful n_topics=1 ok=True 2.181s
  [288/2656] row_id=2753 risk=harmful n_topics=1 ok=True 3.032s
  [289/2656] row_id=2767 risk=harmful n_topics=1 ok=True 2.441s
  [290/2656] row_id=2769 risk=harmful n_topics=1 ok=True 1.99s
  [291/2656] row_id=2778 risk=neutral n_topics=1 ok=True 2.112s
  [292/2656] row_id=2786 risk=neutral n_topics=1 ok=True 1.863s
  [293/2656] row_id=2815 risk=harmful n_topics=2 ok=True 3.011s
  [294/2656] row_id=2823 risk=neutral n_topics=2 ok=True 3.63s
  [295/2656] row_id=2826 risk=neutral n_topics=1 ok=True 2.009s
  [296/2656] row_id=2832 risk=neutral n_topics=1 ok=True 2.001s
  [297/2656] row_id=2844 risk=neutral n_topics=2 ok=True 2.897s
  [298/2656] row_id=2867 risk=neutral n_topics=2 ok=True 3.266s
  [299/2656] row_id=2889 risk=harmful n_topics=1 ok=True 2.575s
  [300/2656] row_id=2892 risk=neutral n_topics=2 ok=True 2.935s
  [301/2656] row_id=2909 risk=neutral n_topics=2 ok=True 2.932s
  [302/2656] row_id=2913 risk=harmful n_topics=2 ok=True 3.471s
  [303/2656] row_id=2914 risk=neutral n_topics=1 ok=True 2.614s
  [304/2656] row_id=2921 risk=harmful n_topics=2 ok=True 2.264s
  [305/2656] row_id=2923 risk=neutral n_topics=2 ok=True 3.589s
  [306/2656] row_id=2925 risk=neutral n_topics=1 ok=True 2.557s
  [307/2656] row_id=2933 risk=harmful n_topics=1 ok=True 2.073s
  [308/2656] row_id=2941 risk=harmful n_topics=2 ok=True 4.606s
  [309/2656] row_id=2953 risk=harmful n_topics=1 ok=True 2.329s
  [310/2656] row_id=2957 risk=neutral n_topics=2 ok=True 3.552s
  [311/2656] row_id=2959 risk=harmful n_topics=1 ok=True 2.462s
  [312/2656] row_id=2967 risk=neutral n_topics=2 ok=True 3.36s
  [313/2656] row_id=2984 risk=neutral n_topics=2 ok=True 3.25s
  [314/2656] row_id=2993 risk=neutral n_topics=1 ok=True 2.751s
  [315/2656] row_id=3008 risk=harmful n_topics=1 ok=True 4.045s
  [316/2656] row_id=3009 risk=neutral n_topics=2 ok=True 3.066s
  [317/2656] row_id=3011 risk=neutral n_topics=2 ok=True 2.627s
  [318/2656] row_id=3037 risk=neutral n_topics=1 ok=True 2.176s
  [319/2656] row_id=3056 risk=harmful n_topics=2 ok=True 2.904s
  [320/2656] row_id=3058 risk=harmful n_topics=1 ok=True 2.33s

### D-vs-C — did the nudge raise topic recall without wrecking risk?

In [18]:
cols = ["approach", "n", "topic_macro_f1", "topic_micro_f1", "risk_accuracy",
        "risk_macro_f1", "n_risk_classes_used", "topics_median", "topics_max",
        "dropped_labels", "wall_min"]
order2 = ["C_template_schema_twostage", "D_twostage_recall"]
summary_d = pd.DataFrame([RESULTS[k] for k in order2 if k in RESULTS])[cols]
display(summary_d)

out_csv_d = BASE_DIR / "saul_recall_nudge_compare.csv"
summary_d.to_csv(out_csv_d, index=False)
print("wrote", out_csv_d)
print("\nWatch: topics_median/topic_micro_f1 should RISE vs C; n_risk_classes_used should "
      "stay >1 and dropped_labels stay 0 (nudge must not reintroduce carpet-bombing).")

,approach,n,topic_macro_f1,topic_micro_f1,risk_accuracy,risk_macro_f1,n_risk_classes_used,topics_median,topics_max,dropped_labels,wall_min
0,D_twostage_recall,2656,0.292,0.303,0.451,0.326,3,1.0,3,0,120.76

wrote /Users/riki/Coding Projects/Thesis/lawgic/generated_files/lawgic_taxonomy/evaluation_v2/generative_runs/_saul_investigation/saul_recall_nudge_compare.csv

Watch: topics_median/topic_micro_f1 should RISE vs C; n_risk_classes_used should stay >1 and dropped_labels stay 0 (nudge must not reintroduce carpet-bombing).