# 100 Annotated TOS LLM Evaluation
TODO: implement a really dumb and stupid evaluation using cleaned_tos_comments.csv. just use f1 score for now.

## Setup

Import dependencies

In [3]:
import pandas as pd
import numpy as np

In [2]:
DATASET_PATH = '../../datasets/Annotated Terms of Service of 100 Online Platforms/'
GENERATED_FILES_PATH = '../../generated_files/100_tos/'

Prepare the variables and data to give to LLM for reference

1. Variable classifications:

In [4]:
variable_classifications = {
    # Evaluative variables
    "ltd": "Limitation of company's liability",
    "ltd_cap": "Maximal threshold of company's liability", 
    "period": "Limitation period",
    "as_is": "No promises",
    "indemn": "Indemnification clause",
    "c_law": "Choice of law other than user's domicile",
    "c_forum": "Choice of forum other than user's domicile",
    "arb": "Mandatory arbitration",
    "class": "Class action waiver",
    "contr_chg": "Unilateral change of contract",
    "price_chg": "Unilateral change of future prices",
    "serv_chg": "Unilateral change of service by the company",
    "acc_del": "Account deletion and unilateral termination of contract by the company",
    "transfer": "Transfer of contractual rights to another subject",
    "cnt_del": "User content deletion",
    "acc_sus": "Account suspension",
    "recom": "Main parameters used in recommender systems",
    "com_sys": "Internal complaint-handling system",
    "cnt_retr": "Retrieval of digital content by the user",
    "IP": "Excessive user content IP license",
    "discret": "Discretional power to interpret the ToS",
    "interpret": "General interpretation clause",
    "sever": "Severability clauses",
    "suggest": "Right to incorporate user's feedback or suggestions without compensation",
    
    # Count variables
    "uncle": "Unclear law clause",
    "docu": "Other documents",
    
    # Pull-out text variables
    "core": "Promises and obligations",
    "what": "Description of the service",
    
    # Metadata
    "name": "Name of the service",
    "url": "ToS URL",
    "date": "Date effective",
    "lang": "ToS Language",
    "sector": "Service sector",
    "word_cnt": "Number of words",
    "hq": "Company's headquarter",
    "hq_cat": "Headquarter category",
    "public": "Publicly listed",
    "paid": "Paid or free services"
}

Grab the scoring system from `Variables Definitions.xlsx` and the meanings for each score.

In [9]:
evaluative_var_df = pd.read_excel(DATASET_PATH + 'Variables Definitions.xlsx', sheet_name="Evaluative Variables")
evaluative_var_df.head()

,General category,Variable name,Legal ground,Code,Score,Detailed description
0,Limitation of remedy clauses,Limitation of company's liability,Annex 1(a) Directive 93/13,ltd,-1.0,Unlawful limitation of liablility for damages ...
1,NaN,NaN,NaN,NaN,0.0,Lawful limitation - any other than unlawful li...
2,NaN,NaN,NaN,NaN,1.0,Lack of limitation
3,NaN,Maximal threshold of company's liability,Annex 1(a) Directive 93/13,ltd_cap,-1.0,Everyone entitled to the damages connected wit...
4,NaN,NaN,NaN,NaN,0.0,Only Businesses entitled to the damages connec...

In [11]:
count_var_df = pd.read_excel(DATASET_PATH + 'Variables Definitions.xlsx', sheet_name="Count Variables")
count_var_df.head()

,Variable name,Code,Short description
0,Unclear law clause,uncle,Number of clauses making it hard for the consu...
1,Other documents,docu,Number of legal documents other than ToS that ...

In [12]:
pull_out_text_df = pd.read_excel(DATASET_PATH + 'Variables Definitions.xlsx', sheet_name="Pull-out Text Variables")
pull_out_text_df.head()

,Variable name,Code,Short description
0,Promises and obligations,core,Any contractual duties or commitments of the c...
1,Description of the service,what,"Clauses that describe functionalities, feature..."

In [13]:
metadata_df = pd.read_excel(DATASET_PATH + 'Variables Definitions.xlsx', sheet_name="Metadata")
metadata_df.head()

,Variable name,Code,Short description
0,Name of the service,name,The name of the service of which the Terms of ...
1,ToS URL,url,"Link to a page, from which Terms of Service ha..."
2,Date effective,date,Date from which the Terms of Service applies
3,ToS Language,lang,The language in which the Terms of Service was...
4,Service sector,sector,Market sector of the service which the analyze...

What does model need to determine:
- which variable name (or the code)
- what score to give. 

WHAT if we just do score first. give it the variable name already.

(skip count, pull-out text, and metadata for now?)

## Start LLM evaluation Pipeline here:

In [6]:
import os
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv

from pydantic import BaseModel, Field
from langchain_ollama import ChatOllama
from langchain_core.prompts import PromptTemplate

load_dotenv()

OLLAMA_API_KEY = os.environ.get("OLLAMA_API_KEY")

if not OLLAMA_API_KEY:
    print("OLLAMA_API_KEY is still not set. Check .env path/value, then re-run this cell.")

In [9]:
import re
from pathlib import Path

comments_rel = Path("generated_files/100_tos/cleaned_tos_comments.csv")
results_rel = Path("datasets/Annotated Terms of Service of 100 Online Platforms/Terms of Service Analysis and Evaluation_RESULTS.csv")
rubric_rel = Path("datasets/Annotated Terms of Service of 100 Online Platforms/Variables Definitions.xlsx")

candidate_roots = [Path.cwd(), Path.cwd().parent, Path.cwd().parent.parent]
repo_root = None
for root in candidate_roots:
    if (root / comments_rel).exists() and (root / results_rel).exists() and (root / rubric_rel).exists():
        repo_root = root
        break

if repo_root is None:
    raise FileNotFoundError("Could not resolve repository root containing required evaluation files.")

comments_path = repo_root / comments_rel
results_path = repo_root / results_rel
rubric_path = repo_root / rubric_rel

comments_df = pd.read_csv(comments_path, encoding="utf-8-sig")
comments_df.columns = [str(c).replace("\ufeff", "").strip() for c in comments_df.columns]

results_df = pd.read_csv(results_path, sep=";", encoding="utf-8-sig")
results_df.columns = [str(c).replace("\ufeff", "").strip() for c in results_df.columns]

rubric_df = pd.read_excel(rubric_path, sheet_name="Evaluative Variables")
rubric_df.columns = [str(c).strip() for c in rubric_df.columns]

rubric_df["Code"] = rubric_df["Code"].ffill()
rubric_df["Variable name"] = rubric_df["Variable name"].ffill()
rubric_df = rubric_df.dropna(subset=["Code", "Score", "Detailed description"]).copy()
rubric_df["Code"] = rubric_df["Code"].astype(str).str.strip().str.lower()
rubric_df["Score"] = pd.to_numeric(rubric_df["Score"], errors="coerce")
rubric_df = rubric_df[rubric_df["Score"].isin([-1, 0, 1])].copy()
rubric_df["Score"] = rubric_df["Score"].astype(int)

evaluative_codes = sorted(rubric_df["Code"].unique(), key=len, reverse=True)
# Use single backslashes: \b is regex word boundary (\\b would match literal "\b")
code_pattern = re.compile(
    r"\b(" + "|".join(re.escape(c) for c in evaluative_codes) + r")\b",
    flags=re.IGNORECASE,
)

def extract_classification_code(comment_text: str):
    text = str(comment_text) if pd.notna(comment_text) else ""
    match = code_pattern.search(text)
    if match:
        return match.group(1).lower()
    return None

comments_df["Classification_Code"] = comments_df["comment"].apply(extract_classification_code)
comments_df = comments_df[comments_df["Classification_Code"].isin(set(evaluative_codes))].copy()
comments_df["Company"] = comments_df["company"].astype(str).str.strip()
comments_df["company_norm"] = comments_df["Company"].str.lower().str.strip()

available_eval_codes = [c for c in evaluative_codes if c in results_df.columns]
gt_long_df = results_df.melt(
    id_vars=["name"],
    value_vars=available_eval_codes,
    var_name="Classification_Code",
    value_name="Ground_Truth_Score",
)

gt_long_df["Classification_Code"] = gt_long_df["Classification_Code"].str.lower().str.strip()
gt_long_df["company_norm"] = gt_long_df["name"].astype(str).str.lower().str.strip()
gt_long_df["Ground_Truth_Score"] = pd.to_numeric(gt_long_df["Ground_Truth_Score"], errors="coerce")
gt_long_df = gt_long_df[gt_long_df["Ground_Truth_Score"].isin([-1, 0, 1])].copy()
gt_long_df["Ground_Truth_Score"] = gt_long_df["Ground_Truth_Score"].astype(int)

rubric_text_map = (
    rubric_df.sort_values(["Code", "Score"])
    .groupby("Code")
    .apply(
        lambda g: "\n".join([f"{int(row['Score'])}: {str(row['Detailed description']).strip()}" for _, row in g.iterrows()]),
        include_groups=False  # <-- This silences the warning and future-proofs the code
    )
    .to_dict()
)

merged_df = comments_df.merge(
    gt_long_df[["company_norm", "Classification_Code", "Ground_Truth_Score"]],
    on=["company_norm", "Classification_Code"],
    how="inner",
)

merged_df["Specific_Rubric"] = merged_df["Classification_Code"].map(rubric_text_map)

unified_eval_df = (
    merged_df[["Company", "Classification_Code", "referenced_text", "Specific_Rubric", "Ground_Truth_Score"]]
    .rename(columns={"referenced_text": "Referenced_Text"})
    .dropna(subset=["Referenced_Text", "Specific_Rubric", "Ground_Truth_Score"])
    .reset_index(drop=True)
)

print(f"Resolved repository root: {repo_root}")
print(f"Rows in cleaned comments: {len(pd.read_csv(comments_path, encoding='utf-8-sig'))}")
print(f"Rows after evaluative-code extraction: {len(comments_df)}")
print(f"Rows in unified evaluation dataframe: {len(unified_eval_df)}")
unified_eval_df.head()

Resolved repository root: /Users/riki/Coding Projects/Thesis/lawgic
Rows in cleaned comments: 2640
Rows after evaluative-code extraction: 1565
Rows in unified evaluation dataframe: 1448

,Company,Classification_Code,Referenced_Text,Specific_Rubric,Ground_Truth_Score
0,YouTube,serv_chg,YouTube is constantly changing and improving t...,-1: When the company reserves the right to cha...,0
1,YouTube,cnt_del,If we reasonably believe that any of your Cont...,-1: When a company reserves a right to delete ...,0
2,YouTube,acc_sus,YouTube reserves the right to suspend or termi...,-1: When the company reserves the right to sus...,0
3,YouTube,acc_del,YouTube reserves the right to suspend or termi...,-1: When the company reserves the right to del...,0
4,YouTube,ltd,"To the extent permitted by applicable law, You...",-1: Unlawful limitation of liablility for dama...,0

In [19]:
from typing import Literal

class OrdinalScoreOutput(BaseModel):
    score: Literal[-1, 0, 1] = Field(
        description="Ordinal severity score. Must be exactly one of -1, 0, or 1."
    )

llm = ChatOllama(
    model="gemma4:31b",
    base_url="https://ollama.com",
    temperature=0.0,
    format="json",
    client_kwargs={
        "headers": {
            "Authorization": f"Bearer {OLLAMA_API_KEY}",
        }
    },
)

structured_llm = llm.with_structured_output(OrdinalScoreOutput)

prompt = PromptTemplate.from_template(
    """
You are a strict evaluator for Terms of Service clauses.
Assign exactly one ordinal score: -1, 0, or 1.
Use only provided specific rubric for this classification.
Do not explain reasoning.

Company: {Company}
Classification_Code: {Classification_Code}
Clause:
{Referenced_Text}

Specific_Rubric:
{Specific_Rubric}

Return strict JSON only in this exact shape:
{{"score": -1}}
or
{{"score": 0}}
or
{{"score": 1}}
""".strip()
)

evaluation_chain = prompt | structured_llm
print("LangChain + Ollama Cloud pipeline ready (model: gemma4:31b, format=json).")

LangChain + Ollama Cloud pipeline ready (model: gemma4:31b, format=json).

In [20]:
from sklearn.metrics import f1_score

def _recover_score_from_parse_error(exc: Exception):
    """Recover -1/0/1 when model returns text like `score: 1` instead of JSON."""
    import re

    text = str(exc)
    if "Invalid json output:" not in text:
        return None

    first_line = text.splitlines()[0]
    raw_output = first_line.split("Invalid json output:", 1)[-1].strip()
    match = re.search(r"(?<!\d)(-1|0|1)(?!\d)", raw_output)
    if not match:
        return None
    return int(match.group(1))


def run_llm_evaluation(num_rows: int | None = None, output_filename: str = "evaluated_tos.csv"):
    """
    Run evaluation on unified_eval_df.

    Args:
        num_rows: Number of rows to evaluate. If None, evaluate all rows.
        output_filename: Output CSV filename in generated_files/100_tos.

    Returns:
        final_eval_df, macro_f1_or_none
    """
    if num_rows is None:
        eval_df = unified_eval_df.copy()
    else:
        if num_rows <= 0:
            raise ValueError("num_rows must be a positive integer or None.")
        eval_df = unified_eval_df.head(num_rows).copy()

    total_rows = len(eval_df)
    print(f"Starting inference for {total_rows} rows...")

    predicted_scores = []
    for idx, row in eval_df.iterrows():
        payload = {
            "Company": row["Company"],
            "Classification_Code": row["Classification_Code"],
            "Referenced_Text": row["Referenced_Text"],
            "Specific_Rubric": row["Specific_Rubric"],
        }

        predicted_score = None
        try:
            response = evaluation_chain.invoke(payload)
            predicted_score = int(response.score)
        except Exception as exc:
            recovered_score = _recover_score_from_parse_error(exc)
            if recovered_score in (-1, 0, 1):
                predicted_score = recovered_score
                print(
                    f"[{idx + 1}/{total_rows}] parser recovery used -> {predicted_score}"
                )
            else:
                print(f"[{idx + 1}/{total_rows}] ERROR ({type(exc).__name__}): {exc}")

        predicted_scores.append(predicted_score)
        print(
            f"[{idx + 1}/{total_rows}] "
            f"{row['Company']} | {row['Classification_Code']} -> {predicted_score}"
        )

    final_eval_df = eval_df.copy()
    final_eval_df["Predicted_Score"] = predicted_scores

    output_path = repo_root / "generated_files/100_tos" / output_filename
    output_path.parent.mkdir(parents=True, exist_ok=True)
    final_eval_df.to_csv(output_path, index=False)
    print(f"Saved evaluated rows to: {output_path}")

    valid_mask = (
        final_eval_df["Ground_Truth_Score"].isin([-1, 0, 1])
        & final_eval_df["Predicted_Score"].isin([-1, 0, 1])
    )

    macro_f1 = None
    print(f"Rows included in report: {len(final_eval_df)}")
    if valid_mask.any():
        macro_f1 = f1_score(
            final_eval_df.loc[valid_mask, "Ground_Truth_Score"].astype(int),
            final_eval_df.loc[valid_mask, "Predicted_Score"].astype(int),
            average="macro",
        )
        print(f"Macro F1 (valid predictions only): {macro_f1:.4f}")
        print(f"Valid rows used for F1: {int(valid_mask.sum())}/{len(final_eval_df)}")
    else:
        print("No valid predictions available yet for F1 calculation.")

    return final_eval_df, macro_f1

Test evaluation run

In [ ]:
# Quick test run (example): evaluate first 25 rows
quick_eval_df, quick_macro_f1 = run_llm_evaluation(num_rows=10, output_filename="evaluated_tos_quick.csv")
quick_eval_df

Starting inference for 10 rows...
[1/10] YouTube | serv_chg -> 0
[2/10] YouTube | cnt_del -> 0
[3/10] YouTube | acc_sus -> 0
[4/10] YouTube | acc_del -> 0
[5/10] YouTube | ltd -> 0
[6/10] YouTube | ltd_cap -> -1
[7/10] YouTube | contr_chg -> 1
[8/10] YouTube | sever -> 0
[9/10] SQUARE ENIX | serv_chg -> -1
[10/10] SQUARE ENIX | acc_sus -> -1
Saved evaluated rows to: /Users/riki/Coding Projects/Thesis/lawgic/generated_files/100_tos/evaluated_tos_quick.csv
Rows included in report: 10
Macro F1 (valid predictions only): 0.5524
Valid rows used for F1: 10/10

,Company,Classification_Code,Referenced_Text,Specific_Rubric,Ground_Truth_Score,Predicted_Score
0,YouTube,serv_chg,YouTube is constantly changing and improving t...,-1: When the company reserves the right to cha...,0,0
1,YouTube,cnt_del,If we reasonably believe that any of your Cont...,-1: When a company reserves a right to delete ...,0,0
2,YouTube,acc_sus,YouTube reserves the right to suspend or termi...,-1: When the company reserves the right to sus...,0,0
3,YouTube,acc_del,YouTube reserves the right to suspend or termi...,-1: When the company reserves the right to del...,0,0
4,YouTube,ltd,"To the extent permitted by applicable law, You...",-1: Unlawful limitation of liablility for dama...,0,0
5,YouTube,ltd_cap,YouTube and its Affiliates’ total liability fo...,-1: Everyone entitled to the damages connected...,0,-1
6,YouTube,contr_chg,We may change this Agreement (1) to reflect ch...,-1: When the company reserves the right to cha...,0,1
7,YouTube,sever,If it turns out that a particular term of this...,-1: -\n0: The ToS contains provisions that kee...,0,0
8,SQUARE ENIX,serv_chg,Square Enix may immediately suspend or termina...,-1: When the company reserves the right to cha...,-1,-1
9,SQUARE ENIX,acc_sus,Square Enix may suspend or terminate your Acco...,-1: When the company reserves the right to sus...,-1,-1

Full evaluation run

In [22]:
# Full run (uncomment when ready):
full_eval_df, full_macro_f1 = run_llm_evaluation(output_filename="evaluated_tos_full.csv")
full_eval_df.head()

Starting inference for 1448 rows...
[1/1448] YouTube | serv_chg -> 0
[2/1448] YouTube | cnt_del -> 0
[3/1448] YouTube | acc_sus -> 0
[4/1448] YouTube | acc_del -> 0
[5/1448] YouTube | ltd -> 0
[6/1448] YouTube | ltd_cap -> -1
[7/1448] YouTube | contr_chg -> 1
[8/1448] YouTube | sever -> 0
[9/1448] SQUARE ENIX | serv_chg -> -1
[10/1448] SQUARE ENIX | acc_sus -> -1
[11/1448] SQUARE ENIX | acc_del -> -1
[12/1448] SQUARE ENIX | price_chg -> 0
[13/1448] SQUARE ENIX | cnt_del -> -1
[14/1448] SQUARE ENIX | arb -> -1
[15/1448] SQUARE ENIX | class -> -1
[16/1448] SQUARE ENIX | as_is -> -1
[17/1448] SQUARE ENIX | ltd -> -1
[18/1448] SQUARE ENIX | ltd_cap -> -1
[19/1448] SQUARE ENIX | contr_chg -> -1
[20/1448] SQUARE ENIX | c_law -> -1
[21/1448] SQUARE ENIX | c_forum -> -1
[22/1448] SQUARE ENIX | sever -> 0
[23/1448] Vinted | contr_chg -> 1
[24/1448] Vinted | price_chg -> 0
[25/1448] Vinted | acc_sus -> 0
[26/1448] Vinted | acc_del -> 0
[27/1448] Vinted | acc_sus -> 0
[28/1448] Vinted | acc_sus -> 0
[29/1448] Vinted | ltd_cap -> -1
[30/1448] Vinted | cnt_del -> 0
[31/1448] Vinted | acc_sus -> 0
[32/1448] Vinted | cnt_del -> 0
[33/1448] Vinted | acc_sus -> 0
[34/1448] Vinted | acc_del -> 1
[35/1448] Vinted | cnt_del -> 0
[36/1448] Vinted | acc_sus -> 0
[37/1448] Vinted | cnt_del -> 0
[38/1448] Vinted | c_law -> 1
[39/1448] Vinted | c_forum -> 1
[40/1448] Vinted | com_sys -> 0
[41/1448] Vinted | acc_del -> 0
[42/1448] Vinted | com_sys -> 0
[43/1448] Dailymotion | acc_del -> -1
[44/1448] Dailymotion | contr_chg -> -1
[45/1448] Dailymotion | acc_del -> 1
[46/1448] Dailymotion | as_is -> -1
[47/1448] Dailymotion | serv_chg -> -1
[48/1448] Dailymotion | ltd -> 0
[49/1448] Dailymotion | acc_sus -> 0
[50/1448] Dailymotion | acc_del -> 0
[51/1448] Dailymotion | cnt_del -> 0
[52/1448] Dailymotion | sever -> 0
[53/1448] Dailymotion | c_law -> -1
[54/1448] Dailymotion | c_forum -> -1
[55/1448] Pracuj.pl | acc_sus -> 0
[56/1448] Pracuj.pl | acc_del -> 0
[57/1448] Pracuj.pl | serv_chg -> -1
[58/1448] Pracuj.pl | contr_chg -> -1
[59/1448] Pracuj.pl | cnt_del -> -1
[60/1448] Pracuj.pl | ltd -> -1
[61/1448] Pracuj.pl | acc_sus -> 0
[62/1448] Pracuj.pl | ltd -> -1
[63/1448] Pracuj.pl | com_sys -> 0
[64/1448] Pracuj.pl | acc_del -> 0
[65/1448] Pracuj.pl | contr_chg -> 1
[66/1448] Pracuj.pl | c_law -> -1
[67/1448] Pracuj.pl | c_forum -> -1
[68/1448] Pracuj.pl | recom -> 1
[69/1448] Pracuj.pl | recom -> 0
[70/1448] Oktawave | acc_sus -> 0
[71/1448] Oktawave | period -> 0
[72/1448] Oktawave | acc_del -> 0
[73/1448] Oktawave | cnt_retr -> 0
[74/1448] Oktawave | com_sys -> 0
[75/1448] Oktawave | ltd -> 0
[76/1448] Oktawave | c_law -> -1
[77/1448] Oktawave | contr_chg -> 0
[78/1448] Oktawave | price_chg -> 0
[79/1448] FollowMyHealth | contr_chg -> -1
[80/1448] FollowMyHealth | price_chg -> 0
[81/1448] FollowMyHealth | cnt_del -> -1
[82/1448] FollowMyHealth | recom -> -1
[83/1448] FollowMyHealth | serv_chg -> -1
[84/1448] FollowMyHealth | acc_del -> 0
[85/1448] FollowMyHealth | cnt_del -> 0
[86/1448] FollowMyHealth | cnt_retr -> -1
[87/1448] FollowMyHealth | ltd -> 0
[88/1448] FollowMyHealth | as_is -> -1
[89/1448] FollowMyHealth | ltd -> -1
[90/1448] FollowMyHealth | ltd_cap -> -1
[91/1448] FollowMyHealth | c_law -> -1
[92/1448] FollowMyHealth | c_forum -> -1
[93/1448] FollowMyHealth | sever -> 0
[94/1448] Spotify | recom -> -1
[95/1448] Spotify | serv_chg -> -1
[96/1448] Spotify | price_chg -> 0
[97/1448] Spotify | cnt_del -> -1
[98/1448] Spotify | acc_del -> 0
[99/1448] Spotify | acc_sus -> 0
[100/1448] Spotify | as_is -> -1
[101/1448] Spotify | ltd -> 0
[102/1448] Spotify | ltd_cap -> -1
[103/1448] Spotify | arb -> -1
[104/1448] Spotify | period -> -1
[105/1448] Spotify | c_law -> -1
[106/1448] Spotify | c_forum -> -1
[107/1448] Spotify | class -> -1
[108/1448] Spotify | arb -> -1
[109/1448] Spotify | period -> -1
[110/1448] Spotify | contr_chg -> 1
[111/1448] Spotify | acc_del -> 0
[112/1448] Spotify | contr_chg -> -1
[113/1448] Spotify | sever -> 0
[114/1448] Badoo | acc_sus -> -1
[115/1448] Badoo | acc_del -> -1
[116/1448] Badoo | cnt_del -> 0
[117/1448] Badoo | cnt_del -> -1
[118/1448] Badoo | acc_del -> 0
[119/1448] Badoo | as_is -> -1
[120/1448] Badoo | serv_chg -> -1
[121/1448] Badoo | contr_chg -> -1
[122/1448] Badoo | ltd -> 1
[123/1448] Badoo | ltd_cap -> -1
[124/1448] Badoo | c_law -> -1
[125/1448] Badoo | contr_chg -> -1
[126/1448] Badoo | sever -> 0
[127/1448] Allegro | acc_sus -> -1
[128/1448] Allegro | recom -> 1
[129/1448] Allegro | cnt_del -> 1
[130/1448] Allegro | acc_sus -> 0
[131/1448] Allegro | cnt_del -> 0
[132/1448] Allegro | price_chg -> 0
[133/1448] Allegro | contr_chg -> 0
[134/1448] Allegro | acc_del -> 1
[135/1448] Allegro | com_sys -> 1
[136/1448] Allegro | c_law -> -1
[137/1448] Allegro | c_forum -> 0
[138/1448] Allegro | sever -> 0
[139/1448] Allegro | com_sys -> 0
[140/1448] Snapchat | cnt_del -> 0
[141/1448] Snapchat | recom -> -1
[142/1448] Snapchat | acc_del -> 0
[143/1448] Snapchat | cnt_del -> 0
[144/1448] Snapchat | acc_sus -> 0
[145/1448] Snapchat | acc_del -> 0
[146/1448] Snapchat | cnt_retr -> -1
[147/1448] Snapchat | serv_chg -> -1
[148/1448] Snapchat | serv_chg -> -1
[149/1448] Snapchat | acc_sus -> -1
[150/1448] Snapchat | acc_del -> -1
[151/1448] Snapchat | contr_chg -> -1
[152/1448] Snapchat | as_is -> -1
[153/1448] Snapchat | ltd -> 0
[154/1448] Snapchat | ltd_cap -> -1
[155/1448] Snapchat | arb -> -1
[156/1448] Snapchat | c_forum -> -1
[157/1448] Snapchat | c_law -> -1
[158/1448] Snapchat | sever -> 0
[159/1448] Tinder | serv_chg -> 0
[160/1448] Tinder | contr_chg -> 1
[161/1448] Tinder | serv_chg -> 0
[162/1448] Tinder | acc_del -> 0
[163/1448] Tinder | acc_del -> 0
[164/1448] Tinder | cnt_del -> 0
[165/1448] Tinder | acc_del -> 0
[166/1448] Tinder | acc_del -> 0
[167/1448] Tinder | acc_del -> 0
[168/1448] Tinder | acc_del -> 0
[169/1448] Tinder | acc_del -> 0
[170/1448] Tinder | as_is -> -1
[171/1448] Tinder | ltd -> 0
[172/1448] Tinder | ltd_cap -> -1
[173/1448] Tinder | arb -> -1
[174/1448] Tinder | class -> -1
[175/1448] Tinder | c_law -> -1
[176/1448] Tinder | c_forum -> -1
[177/1448] Tinder | sever -> 0
[178/1448] Viber | contr_chg -> 1
[179/1448] Viber | acc_del -> -1
[180/1448] Viber | acc_sus -> -1
[181/1448] Viber | serv_chg -> -1
[182/1448] Viber | acc_del -> 0
[183/1448] Viber | serv_chg -> -1
[184/1448] Viber | serv_chg -> -1
[185/1448] Viber | price_chg -> 0
[186/1448] Viber | acc_del -> -1
[187/1448] Viber | serv_chg -> -1
[188/1448] Viber | cnt_del -> -1
[189/1448] Viber | cnt_del -> -1
[190/1448] Viber | acc_del -> -1
[191/1448] Viber | acc_sus -> -1
[192/1448] Viber | acc_del -> -1
[193/1448] Viber | acc_del -> -1
[194/1448] Viber | as_is -> -1
[195/1448] Viber | ltd -> -1
[196/1448] Viber | ltd_cap -> -1
[197/1448] Viber | acc_sus -> 0
[198/1448] Viber | cnt_del -> -1
[199/1448] Viber | serv_chg -> -1
[200/1448] Viber | contr_chg -> 1
[201/1448] Viber | c_law -> -1
[202/1448] Viber | arb -> -1
[203/1448] Viber | class -> -1
[204/1448] Viber | sever -> 0
[205/1448] Twitch | contr_chg -> -1
[206/1448] Twitch | as_is -> -1
[207/1448] Twitch | cnt_del -> -1
[208/1448] Twitch | acc_sus -> 0
[209/1448] Twitch | acc_del -> 0
[210/1448] Twitch | acc_sus -> -1
[211/1448] Twitch | acc_del -> -1
[212/1448] Twitch | as_is -> -1
[213/1448] Twitch | ltd -> -1
[214/1448] Twitch | ltd_cap -> -1
[215/1448] Twitch | arb -> -1
[216/1448] Twitch | c_forum -> -1
[217/1448] Twitch | c_law -> -1
[218/1448] Twitch | class -> -1
[219/1448] Twitch | period -> -1
[220/1448] Twitch | sever -> 0
[221/1448] Twitch | serv_chg -> 1
[222/1448] MultiSport | acc_sus -> 0
[223/1448] MultiSport | acc_del -> 1
[224/1448] MultiSport | com_sys -> 1
[225/1448] MultiSport | ltd -> 0
[226/1448] MultiSport | serv_chg -> -1
[227/1448] MultiSport | contr_chg -> 1
[228/1448] MultiSport | c_law -> -1
[229/1448] MultiSport | acc_sus -> 0
[230/1448] MultiSport | acc_sus -> 0
[231/1448] MultiSport | acc_del -> 0
[232/1448] MultiSport | acc_sus -> 0
[233/1448] EliteSingles | recom -> -1
[234/1448] EliteSingles | cnt_del -> 0
[235/1448] EliteSingles | acc_sus -> 0
[236/1448] EliteSingles | acc_del -> 0
[237/1448] EliteSingles | acc_del -> 1
[238/1448] EliteSingles | ltd -> -1
[239/1448] EliteSingles | cnt_del -> 0
[240/1448] EliteSingles | cnt_retr -> -1
[241/1448] Uber | acc_sus -> 0
[242/1448] Uber | price_chg -> 0
[243/1448] Uber | as_is -> -1
[244/1448] Uber | ltd -> 0
[245/1448] Uber | ltd_cap -> -1
[246/1448] Uber | acc_del -> 0
[247/1448] Uber | acc_sus -> 0
[248/1448] Uber | acc_del -> 0
[249/1448] Uber | contr_chg -> 1
[250/1448] Uber | sever -> 0
[251/1448] Uber | c_law -> -1
[252/1448] Uber | c_forum -> 1
[253/1448] trivago | contr_chg -> -1
[254/1448] trivago | cnt_del -> 0
[255/1448] trivago | acc_del -> 0
[256/1448] trivago | as_is -> -1
[257/1448] trivago | ltd -> 0
[258/1448] trivago | contr_chg -> 1
[259/1448] trivago | c_law -> -1
[260/1448] trivago | c_forum -> -1
[261/1448] Bolt | acc_sus -> -1
[262/1448] Bolt | acc_sus -> -1
[263/1448] Bolt | as_is -> -1
[264/1448] Bolt | ltd -> -1
[265/1448] Bolt | ltd_cap -> -1
[266/1448] Bolt | acc_del -> 0
[267/1448] Bolt | acc_del -> 0
[268/1448] Bolt | contr_chg -> 1
[269/1448] Bolt | c_law -> -1
[270/1448] Bolt | c_forum -> -1
[271/1448] Bolt | sever -> 0
[272/1448] Wolt | acc_del -> 0
[273/1448] Wolt | serv_chg -> -1
[274/1448] Wolt | acc_del -> 0
[275/1448] Wolt | as_is -> -1
[276/1448] Wolt | c_law -> 1
[277/1448] Wolt | c_forum -> 1
[278/1448] Wolt | contr_chg -> -1
[279/1448] Ubisoft | serv_chg -> -1
[280/1448] Ubisoft | price_chg -> 0
[281/1448] Ubisoft | serv_chg -> 0
[282/1448] Ubisoft | acc_sus -> 0
[283/1448] Ubisoft | acc_del -> 0
[284/1448] Ubisoft | cnt_del -> 0
[285/1448] Ubisoft | acc_sus -> -1
[286/1448] Ubisoft | acc_del -> -1
[287/1448] Ubisoft | cnt_retr -> -1
[288/1448] Ubisoft | as_is -> -1
[289/1448] Ubisoft | acc_del -> -1
[290/1448] Ubisoft | as_is -> -1
[291/1448] Ubisoft | ltd -> -1
[292/1448] Ubisoft | contr_chg -> 1
[293/1448] Ubisoft | sever -> 0
[294/1448] Ubisoft | c_law -> -1
[295/1448] Ubisoft | c_forum -> -1
[296/1448] ZnanyLekarz | price_chg -> 0
[297/1448] ZnanyLekarz | cnt_del -> 0
[298/1448] ZnanyLekarz | cnt_del -> 0
[299/1448] ZnanyLekarz | cnt_del -> 0
[300/1448] ZnanyLekarz | acc_del -> 0
[301/1448] ZnanyLekarz | as_is -> -1
[302/1448] ZnanyLekarz | ltd -> 0
[303/1448] ZnanyLekarz | com_sys -> 0
[304/1448] ZnanyLekarz | contr_chg -> 1
[305/1448] ZnanyLekarz | c_law -> -1
[306/1448] ZnanyLekarz | c_forum -> 0
[307/1448] ZnanyLekarz | cnt_retr -> 1
[308/1448] iCloud | acc_sus -> 0
[309/1448] iCloud | acc_del -> 0
[310/1448] iCloud | contr_chg -> 1
[311/1448] iCloud | serv_chg -> 1
[312/1448] iCloud | ltd -> 0
[313/1448] iCloud | as_is -> -1
[314/1448] iCloud | cnt_del -> -1
[315/1448] iCloud | ltd -> -1
[316/1448] iCloud | acc_sus -> 0
[317/1448] iCloud | cnt_del -> -1
[318/1448] iCloud | acc_del -> -1
[319/1448] iCloud | acc_del -> 0
[320/1448] iCloud | acc_sus -> 0
[321/1448] iCloud | acc_del -> 0
[322/1448] iCloud | acc_sus -> 0
[323/1448] iCloud | cnt_del -> 0
[324/1448] iCloud | ltd -> 0
[325/1448] iCloud | acc_sus -> 0
[326/1448] iCloud | acc_del -> 0
[327/1448] iCloud | acc_sus -> 0
[328/1448] iCloud | acc_del -> 0
[329/1448] iCloud | acc_del -> 0
[330/1448] iCloud | ltd -> 0
[331/1448] iCloud | cnt_retr -> -1
[332/1448] iCloud | as_is -> -1
[333/1448] iCloud | ltd -> -1
[334/1448] iCloud | c_law -> -1
[335/1448] iCloud | c_forum -> -1
[336/1448] iCloud | sever -> 0
[337/1448] HBO GO | acc_del -> 0
[338/1448] HBO GO | serv_chg -> -1
[339/1448] HBO GO | price_chg -> 0
[340/1448] HBO GO | acc_del -> 0
[341/1448] HBO GO | contr_chg -> 1
[342/1448] HBO GO | acc_sus -> 0
[343/1448] HBO GO | acc_del -> 0
[344/1448] HBO GO | acc_del -> 0
[345/1448] HBO GO | contr_chg -> 0
[346/1448] HBO GO | serv_chg -> 0
[347/1448] HBO GO | acc_del -> 0
[348/1448] HBO GO | period -> 0
[349/1448] HBO GO | ltd_cap -> 1
[350/1448] HBO GO | c_law -> -1
[351/1448] KAYAK | contr_chg -> -1
[352/1448] KAYAK | acc_sus -> -1
[353/1448] KAYAK | acc_del -> -1
[354/1448] KAYAK | cnt_del -> -1
[355/1448] KAYAK | as_is -> -1
[356/1448] KAYAK | ltd -> -1
[357/1448] KAYAK | serv_chg -> -1
[358/1448] KAYAK | contr_chg -> -1
[359/1448] KAYAK | sever -> 0
[360/1448] KAYAK | c_law -> -1
[361/1448] KAYAK | c_forum -> -1
[362/1448] KAYAK | class -> -1
[363/1448] PayPal | contr_chg -> -1
[364/1448] PayPal | acc_del -> 0
[365/1448] PayPal | serv_chg -> 0
[366/1448] PayPal | serv_chg -> -1
[367/1448] PayPal | serv_chg -> -1
[368/1448] PayPal | acc_sus -> -1
[369/1448] PayPal | acc_sus -> -1
[370/1448] PayPal | acc_del -> -1
[371/1448] PayPal | acc_sus -> 0
[372/1448] PayPal | acc_sus -> -1
[373/1448] PayPal | ltd -> 0
[374/1448] PayPal | ltd_cap -> -1
[375/1448] PayPal | as_is -> -1
[376/1448] PayPal | c_law -> -1
[377/1448] DoorDash | contr_chg -> -1
[378/1448] DoorDash | acc_sus -> 0
[379/1448] DoorDash | acc_del -> 0
[380/1448] DoorDash | acc_sus -> 0
[381/1448] DoorDash | acc_del -> 0
[382/1448] DoorDash | cnt_del -> -1
[383/1448] DoorDash | acc_sus -> -1
[384/1448] DoorDash | acc_del -> -1
[385/1448] DoorDash | price_chg -> 0
[386/1448] DoorDash | serv_chg -> -1
[387/1448] DoorDash | price_chg -> 0
[388/1448] DoorDash | acc_sus -> -1
[389/1448] DoorDash | acc_del -> -1
[390/1448] DoorDash | arb -> -1
[391/1448] DoorDash | class -> -1
[392/1448] DoorDash | serv_chg -> -1
[393/1448] DoorDash | as_is -> -1
[394/1448] DoorDash | ltd_cap -> -1
[395/1448] DoorDash | ltd -> -1
[396/1448] DoorDash | c_forum -> -1
[397/1448] DoorDash | serv_chg -> -1
[398/1448] DoorDash | acc_sus -> -1
[399/1448] DoorDash | acc_del -> -1
[400/1448] DoorDash | c_law -> -1
[401/1448] DoorDash | sever -> 0
[402/1448] PayPay | as_is -> -1
[403/1448] PayPay | serv_chg -> -1
[404/1448] PayPay | cnt_del -> -1
[405/1448] PayPay | acc_sus -> -1
[406/1448] PayPay | acc_del -> -1
[407/1448] PayPay | cnt_retr -> -1
[408/1448] PayPay | acc_del -> -1
[409/1448] PayPay | as_is -> -1
[410/1448] PayPay | ltd -> 0
[411/1448] PayPay | ltd_cap -> -1
[412/1448] PayPay | serv_chg -> -1
[413/1448] PayPay | contr_chg -> 0
[414/1448] PayPay | c_law -> -1
[415/1448] PayPay | c_forum -> -1
[416/1448] PayPay | sever -> 0
[417/1448] Discord | contr_chg -> 0
[418/1448] Discord | serv_chg -> -1
[419/1448] Discord | acc_sus -> 0
[420/1448] Discord | acc_del -> 0
[421/1448] Discord | cnt_del -> -1
[422/1448] Discord | acc_del -> -1
[423/1448] Discord | acc_sus -> -1
[424/1448] Discord | acc_sus -> 0
[425/1448] Discord | acc_del -> 0
[426/1448] Discord | acc_del -> -1
[427/1448] Discord | cnt_retr -> -1
[428/1448] Discord | as_is -> -1
[429/1448] Discord | ltd -> 0
[430/1448] Discord | ltd_cap -> -1
[431/1448] Discord | price_chg -> 0
[432/1448] Discord | arb -> -1
[433/1448] Discord | class -> -1
[434/1448] Discord | c_law -> -1
[435/1448] Discord | c_forum -> -1
[436/1448] Discord | sever -> 0
[437/1448] Amazon | acc_del -> 0
[438/1448] Amazon | acc_del -> 1
[439/1448] Amazon | cnt_del -> 0
[440/1448] Amazon | ltd -> 0
[441/1448] Amazon | c_law -> -1
[442/1448] Amazon | c_forum -> 1
[443/1448] Amazon | contr_chg -> 1
[444/1448] Amazon | serv_chg -> -1
[445/1448] Amazon | acc_del -> 1
[446/1448] Amazon | ltd -> 0
[447/1448] Amazon | c_law -> -1
[448/1448] Amazon | c_forum -> 1
[449/1448] Amazon | contr_chg -> -1
[450/1448] Amazon | sever -> 0
[451/1448] Maya | contr_chg -> -1
[452/1448] Maya | acc_sus -> 0
[453/1448] Maya | acc_del -> 0
[454/1448] Maya | serv_chg -> -1
[455/1448] Maya | price_chg -> 0
[456/1448] Maya | ltd -> -1
[457/1448] Maya | as_is -> -1
[458/1448] Maya | acc_sus -> -1
[459/1448] Maya | acc_del -> -1
[460/1448] Maya | ltd -> -1
[461/1448] Maya | acc_del -> 0
[462/1448] Maya | ltd -> -1
[463/1448] Maya | acc_del -> 0
[464/1448] Maya | as_is -> -1
[465/1448] Maya | ltd -> -1
[466/1448] Maya | ltd_cap -> -1
[467/1448] Maya | serv_chg -> -1
[468/1448] Maya | sever -> 0
[469/1448] Maya | c_law -> -1
[470/1448] Maya | c_forum -> -1
[471/1448] TikTok | recom -> -1
[472/1448] TikTok | serv_chg -> 1
[473/1448] TikTok | contr_chg -> 1
[474/1448] TikTok | acc_sus -> -1
[475/1448] TikTok | acc_del -> -1
[476/1448] TikTok | cnt_retr -> -1
[477/1448] TikTok | acc_sus -> -1
[478/1448] TikTok | acc_del -> -1
[479/1448] TikTok | cnt_del -> 0
[480/1448] TikTok | as_is -> -1
[481/1448] TikTok | cnt_del -> 0
[482/1448] TikTok | as_is -> -1
[483/1448] TikTok | serv_chg -> 0
[484/1448] TikTok | ltd -> 0
[485/1448] TikTok | ltd_cap -> -1
[486/1448] TikTok | c_law -> -1
[487/1448] TikTok | c_forum -> -1
[488/1448] TikTok | sever -> 0
[489/1448] Lyft | contr_chg -> -1
[490/1448] Lyft | price_chg -> 0
[491/1448] Lyft | acc_del -> 0
[492/1448] Lyft | as_is -> -1
[493/1448] Lyft | ltd -> -1
[494/1448] Lyft | acc_del -> 0
[495/1448] Lyft | acc_sus -> 1
[496/1448] Lyft | arb -> -1
[497/1448] Lyft | class -> -1
[498/1448] Lyft | sever -> 0
[499/1448] Lyft | c_law -> -1
[500/1448] Sleep Cycle | as_is -> -1
[501/1448] Sleep Cycle | ltd -> 0
[502/1448] Sleep Cycle | price_chg -> 0
[503/1448] Sleep Cycle | contr_chg -> -1
[504/1448] Crypto.com | contr_chg -> -1
[505/1448] Crypto.com | contr_chg -> -1
[506/1448] Crypto.com | acc_sus -> -1
[507/1448] Crypto.com | acc_del -> -1
[508/1448] Crypto.com | as_is -> -1
[509/1448] Crypto.com | acc_sus -> 0
[510/1448] Crypto.com | acc_del -> 0
[511/1448] Crypto.com | contr_chg -> -1
[512/1448] Crypto.com | ltd -> 0
[513/1448] Crypto.com | ltd_cap -> -1
[514/1448] Crypto.com | acc_del -> 0
[515/1448] Crypto.com | acc_del -> 0
[516/1448] Crypto.com | acc_sus -> -1
[517/1448] Crypto.com | sever -> 0
[518/1448] Crypto.com | com_sys -> 0
[519/1448] Crypto.com | com_sys -> 0
[520/1448] Crypto.com | c_law -> -1
[521/1448] Crypto.com | arb -> -1
[522/1448] Crypto.com | acc_sus -> -1
[523/1448] Crypto.com | acc_del -> -1
[524/1448] Crypto.com | acc_del -> 0
[525/1448] Crypto.com | acc_del -> 0
[526/1448] Quora | acc_sus -> -1
[527/1448] Quora | acc_del -> -1
[528/1448] Quora | serv_chg -> -1
[529/1448] Quora | cnt_del -> -1
[530/1448] Quora | cnt_del -> -1
[531/1448] Quora | recom -> -1
[532/1448] Quora | as_is -> -1
[533/1448] Quora | ltd -> 0
[534/1448] Quora | ltd_cap -> -1
[535/1448] Quora | c_law -> -1
[536/1448] Quora | c_forum -> -1
[537/1448] Quora | contr_chg -> -1
[538/1448] Quora | sever -> 0
[539/1448] iTaxi | acc_sus -> 0
[540/1448] iTaxi | acc_sus -> 0
[541/1448] iTaxi | serv_chg -> -1
[542/1448] iTaxi | ltd -> 0
[543/1448] iTaxi | cnt_del -> 0
[544/1448] iTaxi | com_sys -> 1
[545/1448] iTaxi | sever -> 0
[546/1448] iTaxi | contr_chg -> -1
[547/1448] iTaxi | c_law -> -1
[548/1448] Steam | serv_chg -> 1
[549/1448] Steam | acc_del -> -1
[550/1448] Steam | serv_chg -> -1
[551/1448] Steam | price_chg -> 0
[552/1448] Steam | acc_del -> 0
[553/1448] Steam | cnt_del -> -1
[554/1448] Steam | as_is -> -1
[555/1448] Steam | ltd -> -1
[556/1448] Steam | contr_chg -> -1
[557/1448] Steam | acc_del -> 0
[558/1448] Steam | c_law -> -1
[559/1448] Steam | c_forum -> -1
[560/1448] Steam | arb -> -1
[561/1448] Steam | class -> -1
[562/1448] Steam | sever -> 0
[563/1448] Keep | arb -> -1
[564/1448] Keep | contr_chg -> -1
[565/1448] Keep | serv_chg -> -1
[566/1448] Keep | acc_del -> -1
[567/1448] Keep | ltd -> 0
[568/1448] Keep | as_is -> -1
[569/1448] Keep | ltd -> -1
[570/1448] Keep | ltd_cap -> -1
[571/1448] Keep | acc_sus -> -1
[572/1448] Keep | acc_del -> -1
[573/1448] Keep | serv_chg -> 0
[574/1448] Keep | cnt_retr -> -1
[575/1448] Keep | price_chg -> 0
[576/1448] Keep | c_law -> -1
[577/1448] Keep | sever -> 0
[578/1448] Pyszne.pl | acc_del -> 1
[579/1448] Pyszne.pl | com_sys -> 1
[580/1448] Pyszne.pl | c_law -> 1
[581/1448] MyFitnessPal | serv_chg -> -1
[582/1448] MyFitnessPal | ltd -> 0
[583/1448] MyFitnessPal | acc_sus -> -1
[584/1448] MyFitnessPal | acc_sus -> -1
[585/1448] MyFitnessPal | acc_del -> -1
[586/1448] MyFitnessPal | cnt_del -> -1
[587/1448] MyFitnessPal | acc_del -> 0
[588/1448] MyFitnessPal | acc_sus -> 0
[589/1448] MyFitnessPal | acc_del -> 0
[590/1448] MyFitnessPal | cnt_del -> 0

,Company,Classification_Code,Referenced_Text,Specific_Rubric,Ground_Truth_Score,Predicted_Score
0,YouTube,serv_chg,YouTube is constantly changing and improving t...,-1: When the company reserves the right to cha...,0,0
1,YouTube,cnt_del,If we reasonably believe that any of your Cont...,-1: When a company reserves a right to delete ...,0,0
2,YouTube,acc_sus,YouTube reserves the right to suspend or termi...,-1: When the company reserves the right to sus...,0,0
3,YouTube,acc_del,YouTube reserves the right to suspend or termi...,-1: When the company reserves the right to del...,0,0
4,YouTube,ltd,"To the extent permitted by applicable law, You...",-1: Unlawful limitation of liablility for dama...,0,0